// Copyright NU Cybernetics. p(DOOM) — research prototype.
/**
 * Objects written by the Go model run and promoted into a release directory
 * (build-spec §3.6). These schemas mirror `internal/schema/release.go`
 * field-for-field: Go is the producer, TypeScript the consumer. The sample in
 * `test/release-sample/` is generated by `pdoomctl` from the synthetic fixture
 * snapshot and pins the contract.
 */
import { z } from "zod";
import {
  Base64String,
  DateString,
  DateTimeString,
  ModelVersion,
  NonEmptyString,
  NonNegativeInt,
  IndexScore,
  Probability,
  QuantilesSchema,
  ReleaseId,
  Sha256Hex,
  SnapshotId,
  SourceId,
  UnitInterval,
  checkQuantilesMonotonic,
} from "./common";
import {
  AggregationMethod,
  EditorialRiskLevel,
  EstimateStatus,
  ForecastHorizon,
  Horizon,
  IndexId,
  Outcome,
  SensitivityKind,
  UncertaintyLabel,
} from "./enums";

const CommitOrUncommitted = z.union([
  z.string().regex(/^[a-f0-9]{7,40}$/, "expected a git commit hash"),
  z.literal("uncommitted"),
]);

const EstimateIdString = z.string().regex(/^est-[A-Za-z0-9_+-]+$/, "expected an estimate id");

// ---------------------------------------------------------------------------
// Estimate
// ---------------------------------------------------------------------------

export const EstimateDisplaySchema = z.strictObject({
  central: NonEmptyString.describe('Rounded central value or "Insufficiently calibrated"'),
  interval: z.string().describe("Rounded p05–p95 interval; empty when no probability is published"),
  note: z.string(),
});
export type EstimateDisplay = z.infer<typeof EstimateDisplaySchema>;

export const SourceCoverageSchema = z.strictObject({
  forecast_count: NonNegativeInt,
  population_count: NonNegativeInt,
  source_ids: z.array(SourceId),
});
export type SourceCoverage = z.infer<typeof SourceCoverageSchema>;

export const PreviousEstimateSchema = z.strictObject({
  release_id: ReleaseId,
  p50: Probability.nullable(),
  display: z.string(),
});
export type PreviousEstimate = z.infer<typeof PreviousEstimateSchema>;

export const RoundingRuleName = z
  .string()
  .regex(/^(none|nearest_\d+)$/, 'expected "none" or "nearest_<points>"');

export const EstimateSchema = z
  .strictObject({
    estimate_id: EstimateIdString,
    producer: ModelVersion,
    status: EstimateStatus,
    outcome_set: z.array(Outcome).min(1),
    outcome_label: NonEmptyString,
    horizon: Horizon,
    horizon_note: z.string().nullable(),
    conditioning: z.string(),
    forecast_origin_date: DateString,
    last_evidence_date: DateString,
    quantiles: QuantilesSchema.nullable(),
    mean: Probability.nullable(),
    disagreement: UncertaintyLabel.nullable(),
    uncertainty: UncertaintyLabel,
    model_confidence: z.string(),
    source_coverage: SourceCoverageSchema,
    previous: PreviousEstimateSchema.nullable(),
    reason_for_change: z.string(),
    rounding_rule: RoundingRuleName,
    display: EstimateDisplaySchema,
    assumptions: z.array(z.string()),
    method_ref: NonEmptyString,
    group_id: z.string().nullable(),
  })
  .superRefine((value, ctx) => {
    checkQuantilesMonotonic(value.quantiles, ctx);
    if (value.status === "insufficiently_calibrated" && (value.quantiles !== null || value.mean !== null)) {
      ctx.addIssue({
        code: "custom",
        message: "an insufficiently_calibrated estimate publishes no quantiles or mean",
        path: ["quantiles"],
      });
    }
    if (value.status !== "insufficiently_calibrated" && value.quantiles === null) {
      ctx.addIssue({ code: "custom", message: "a published estimate needs quantiles", path: ["quantiles"] });
    }
  })
  .describe("Published estimate with outcome, horizon, conditioning, interval and status");
export type Estimate = z.infer<typeof EstimateSchema>;

// ---------------------------------------------------------------------------
// IndexValue
// ---------------------------------------------------------------------------

export const IndexComponentSchema = z.strictObject({
  signal_id: NonEmptyString.describe("Signal id, incident id or component name"),
  weight: z.number(),
  value_normalized: z.number(),
  tier: z.int().min(0).max(5),
  contribution: z.number(),
});
export type IndexComponent = z.infer<typeof IndexComponentSchema>;

export const IndexBaselineSchema = z.strictObject({
  snapshot_id: z.string(),
  release_id: z.string(),
  value: IndexScore.nullable(),
});
export type IndexBaseline = z.infer<typeof IndexBaselineSchema>;

export const IndexValueSchema = z
  .strictObject({
    index_id: IndexId,
    value: IndexScore.nullable(),
    label: NonEmptyString,
    scale: NonEmptyString,
    is_probability: z.literal(false),
    baseline: IndexBaselineSchema.nullable(),
    components: z.array(IndexComponentSchema),
    coverage: UnitInterval,
    as_of: DateString,
    method_ref: NonEmptyString,
    note: z.string(),
  })
  .describe("Index value on the 0–100 scale; never a probability");
export type IndexValue = z.infer<typeof IndexValueSchema>;

// ---------------------------------------------------------------------------
// AggregationResult
// ---------------------------------------------------------------------------

export const AggregationResultSchema = z
  .strictObject({
    aggregation_id: NonEmptyString,
    group_id: NonEmptyString,
    method: AggregationMethod,
    preferred: z.boolean(),
    outcome_set: z.array(Outcome).min(1),
    horizon: ForecastHorizon,
    conditioning: z.string(),
    value: Probability,
    n: z.int().min(2),
    forecast_ids: z.array(z.string()),
    source_ids: z.array(SourceId),
    population_count: NonNegativeInt,
    weights: z.record(z.string(), z.number()),
    wording_note: z.string(),
    transformation_note: z.string(),
    note: z.string(),
  })
  .describe("Aggregate of one compatibility group under one method");
export type AggregationResult = z.infer<typeof AggregationResultSchema>;

// ---------------------------------------------------------------------------
// SensitivityRun
// ---------------------------------------------------------------------------

export const SensitivityRunSchema = z
  .strictObject({
    run_id: NonEmptyString,
    kind: SensitivityKind,
    target_kind: z.enum(["aggregation_group", "estimate"]),
    target_id: NonEmptyString,
    removed_id: z.string().nullable(),
    parameter_change: z.string(),
    horizon: z.string().nullable(),
    outcome_set: z.array(Outcome),
    baseline_value: Probability,
    value: Probability,
    delta: z.number().min(-1).max(1).describe("value - baseline_value"),
    rank: z.int().min(1),
    note: z.string(),
  })
  .superRefine((value, ctx) => {
    if (Math.abs(value.value - value.baseline_value - value.delta) > 2e-6) {
      ctx.addIssue({ code: "custom", message: "delta must equal value - baseline_value", path: ["delta"] });
    }
  })
  .describe("One perturbation of the model and its effect on a target");
export type SensitivityRun = z.infer<typeof SensitivityRunSchema>;

// ---------------------------------------------------------------------------
// DeltaRecord (PROBABILITY CHANGE POLICY)
// ---------------------------------------------------------------------------

export const EstimateChangeSchema = z.strictObject({
  estimate_id: EstimateIdString,
  status: z.string(),
  previous_p50: Probability.nullable(),
  new_p50: Probability.nullable(),
  change_points: z.number().nullable().describe("(new − previous) × 100"),
  previous_display: z.string(),
  new_display: z.string(),
});
export type EstimateChange = z.infer<typeof EstimateChangeSchema>;

export const IndexChangeSchema = z.strictObject({
  index_id: IndexId,
  previous: IndexScore.nullable(),
  new: IndexScore.nullable(),
  delta: z.number().nullable(),
});
export type IndexChange = z.infer<typeof IndexChangeSchema>;

export const DeltaRecordSchema = z
  .strictObject({
    kind: z.literal("delta_record"),
    schema_version: z.literal(1),
    release_id: ReleaseId.nullable(),
    previous_release_id: ReleaseId.nullable(),
    snapshot_id: SnapshotId,
    previous_snapshot_id: SnapshotId.nullable(),
    generated_at: DateTimeString,
    estimate_changes: z.array(EstimateChangeSchema),
    index_changes: z.array(IndexChangeSchema),
    heightened_review_triggers: z.array(z.string()),
    new_scenario_ids: z.array(z.string()),
    new_forecast_source_ids: z.array(z.string()),
    redefined_benchmark_ids: z.array(z.string()),
    model_version_changed: z.boolean(),
    notes: z.array(z.string()),
  })
  .describe("PROBABILITY CHANGE POLICY record versus the previous release");
export type DeltaRecord = z.infer<typeof DeltaRecordSchema>;

// ---------------------------------------------------------------------------
// DriversExplained ("Why this number?")
// ---------------------------------------------------------------------------

export const ContributionDirection = z.enum(["raises_pressure", "strengthens_control"]);

export const DriversExplainedItemSchema = z
  .strictObject({
    index_id: IndexId,
    driver: NonEmptyString.describe("Signal id"),
    driver_family: z.string(),
    direction: ContributionDirection,
    magnitude: z.number().describe("Contribution in index points"),
    source_ids: z.array(SourceId),
    confidence: UnitInterval,
    model_role: z.string(),
    last_updated: DateString,
    sensitivity: z.number().describe("Index points moved when this signal is removed"),
    counterevidence: z.string().nullable(),
  })
  .describe("One driver contribution shown in the 'Why this number?' panel");
export type DriversExplainedItem = z.infer<typeof DriversExplainedItemSchema>;

export const DriversExplainedSchema = z
  .strictObject({
    kind: z.literal("drivers_explained"),
    schema_version: z.literal(1),
    release_id: ReleaseId.nullable(),
    as_of: DateString,
    items: z.array(DriversExplainedItemSchema),
    notes: z.array(z.string()),
  })
  .describe("drivers_explained.json");
export type DriversExplained = z.infer<typeof DriversExplainedSchema>;

// ---------------------------------------------------------------------------
// ReleaseManifest (MODEL RELEASE ARTIFACT)
// ---------------------------------------------------------------------------

export const EstimateSummarySchema = z.strictObject({
  estimate_id: EstimateIdString,
  status: EstimateStatus,
  outcome_set: z.array(Outcome).min(1),
  horizon: Horizon,
  p50: Probability.nullable(),
  interval: QuantilesSchema.nullable(),
  display: NonEmptyString,
});
export type EstimateSummary = z.infer<typeof EstimateSummarySchema>;

export const SensitivitySummarySchema = z.strictObject({
  run_id: NonEmptyString,
  kind: SensitivityKind,
  target_id: NonEmptyString,
  delta: z.number(),
});
export type SensitivitySummary = z.infer<typeof SensitivitySummarySchema>;

export const ExternalForecastSummarySchema = z.strictObject({
  group_count: NonNegativeInt,
  forecast_count: NonNegativeInt,
  source_ids: z.array(SourceId),
  group_ids: z.array(z.string()),
});
export type ExternalForecastSummary = z.infer<typeof ExternalForecastSummarySchema>;

export const ApprovalPolicySchema = z.strictObject({
  required_approvals: NonNegativeInt,
  received_approvals: NonNegativeInt,
  heightened_review: z.boolean(),
  heightened_review_ack: z.string().nullable(),
  approver_ids: z.array(z.string()),
});
export type ApprovalPolicy = z.infer<typeof ApprovalPolicySchema>;

export const SupersededSchema = z.strictObject({ by: ReleaseId, at: DateTimeString });

export const DataSummarySchema = z.strictObject({
  scenario_ids: z.array(z.string()),
  forecast_source_ids: z.array(z.string()),
  benchmark_definitions: z.record(z.string(), z.string()),
  forecast_count: NonNegativeInt,
  source_count: NonNegativeInt,
  incident_count: NonNegativeInt,
});
export type DataSummary = z.infer<typeof DataSummarySchema>;

export const ReleaseFileSchema = z.strictObject({ path: NonEmptyString, sha256: Sha256Hex, count: NonNegativeInt });

export const ReleaseManifestSchema = z
  .strictObject({
    release_id: ReleaseId,
    candidate_id: z.string().regex(/^cand-\d{4}-\d{2}-\d{2}-\d{3}$/),
    previous_release_id: ReleaseId.nullable(),
    model_versions: z.array(ModelVersion).min(1),
    code_commit: CommitOrUncommitted,
    data_snapshot: SnapshotId,
    source_cutoff: DateString,
    generated_at: DateTimeString,
    outcome_definition: NonEmptyString,
    horizons: z.array(Horizon).min(1),
    priors: z.record(z.string(), z.unknown()),
    weights: z.record(z.string(), z.unknown()),
    dependencies: z.record(z.string(), z.unknown()),
    estimates: z.array(EstimateSummarySchema),
    intervals: z.string(),
    sensitivity: z.array(SensitivitySummarySchema),
    external_forecasts: ExternalForecastSummarySchema,
    changes: z.array(z.string()),
    editorial_risk_level: EditorialRiskLevel,
    uncertainty_score: IndexScore.nullable(),
    data_summary: DataSummarySchema,
    reviewers: z.array(z.string()),
    approval: ApprovalPolicySchema.nullable(),
    known_limitations: z.array(z.string()),
    reproduction_command: NonEmptyString,
    files: z.array(ReleaseFileSchema),
    signature: Sha256Hex.describe("SHA-256 of the canonical manifest with publication fields cleared; reviewers sign it"),
    published: DateTimeString.nullable(),
    superseded: SupersededSchema.nullable(),
  })
  .superRefine((value, ctx) => {
    if (value.published !== null) {
      if (value.approval === null || value.approval.received_approvals < value.approval.required_approvals) {
        ctx.addIssue({ code: "custom", message: "a published release must carry sufficient approvals", path: ["approval"] });
      }
      if (value.reviewers.length === 0) {
        ctx.addIssue({ code: "custom", message: "a published release lists its reviewers", path: ["reviewers"] });
      }
    }
  })
  .describe("MODEL RELEASE ARTIFACT manifest");
export type ReleaseManifest = z.infer<typeof ReleaseManifestSchema>;

// ---------------------------------------------------------------------------
// Approval (approvals.json item) and release summaries
// ---------------------------------------------------------------------------

export const ApprovalSchema = z
  .strictObject({
    reviewer_id: NonEmptyString,
    key_id: NonEmptyString,
    signed_at: DateTimeString,
    manifest_sha256: Sha256Hex,
    signature_base64: Base64String,
    conflicts_declared: z.string(),
  })
  .describe("Signed reviewer approval of a release manifest");
export type Approval = z.infer<typeof ApprovalSchema>;

export const ReleaseSummarySchema = z.strictObject({
  release_id: ReleaseId,
  data_snapshot: SnapshotId,
  model_versions: z.array(ModelVersion),
  published: DateTimeString.nullable(),
  superseded: SupersededSchema.nullable(),
  is_current: z.boolean(),
});
export type ReleaseSummary = z.infer<typeof ReleaseSummarySchema>;

/** A fully loaded release directory as served by the SDK and the API. */
export const ReleaseSchema = z.strictObject({
  manifest: ReleaseManifestSchema,
  estimates: z.array(EstimateSchema),
  indexes: z.array(IndexValueSchema),
  aggregations: z.array(AggregationResultSchema),
  sensitivity: z.array(SensitivityRunSchema),
  delta: DeltaRecordSchema,
  drivers_explained: DriversExplainedSchema,
  approvals: z.array(ApprovalSchema),
});
export type Release = z.infer<typeof ReleaseSchema>;
