// Copyright NU Cybernetics. p(DOOM) — research prototype.
import { review } from "./helpers.mjs";

function fc(id, o) {
  return {
    id,
    forecaster_or_survey: o.who,
    source_id: o.source,
    date: o.date,
    population: o.population,
    sample_size: o.n ?? null,
    expertise: o.expertise,
    question_wording_original: o.wording,
    paraphrase: o.paraphrase ?? false,
    outcome_set: o.outcomes,
    horizon: o.horizon,
    horizon_note: o.horizon_note ?? null,
    horizon_end_year: o.end_year ?? null,
    conditions: o.conditions,
    mean: o.mean ?? null,
    median: o.median ?? null,
    quantiles: o.quantiles ?? null,
    response_rate: o.response_rate ?? null,
    selection_effects: o.selection ?? null,
    framing_effects: o.framing ?? null,
    calibration: o.calibration ?? null,
    group_id: o.group ?? null,
    transformation_note: o.transformation ?? null,
    status: "current",
    ...review(o.verified ?? "search"),
  };
}

const PDOOM_SET = ["O3", "O4", "O5", "O6", "O7", "O8"];

export const forecasts = [
  fc("fc-espai-2022-extremely-bad-long-run", { who: "2022 Expert Survey on Progress in AI (AI Impacts)", source: "src-aiimpacts-2022-espai", date: "2022-08-03", population: "general_ai_researchers", n: 738, expertise: "Authors at NeurIPS/ICML 2021", wording: "How likely is it that the long-run effect of advanced AI on humanity will be extremely bad (e.g., human extinction)?", paraphrase: true, outcomes: PDOOM_SET, horizon: "eventual", horizon_note: "'Long-run effect' with no endpoint; treated as eventual.", conditions: "Conditional on high-level machine intelligence existing (survey framing).", median: 0.05, response_rate: 0.17, selection: "Self-selected respondents among invited authors; 48% gave at least 10%, 25% gave 0%.", framing: "Answers depended on whether respondents were asked about extinction directly or as one of several outcomes.", calibration: "Not a forecasting-trained population; no scoring possible.", group: "G-XBAD-LONG-RUN", transformation: "'Extremely bad (e.g., human extinction)' mapped to the combined p(DOOM) set O3–O8 because respondents were not asked to separate extinction from other irreversible outcomes." }),
  fc("fc-espai-2023-extremely-bad-long-run", { who: "2023 Expert Survey on Progress in AI (Grace et al. 2024)", source: "src-grace-2024-thousands-of-ai-authors", date: "2023-10-15", population: "general_ai_researchers", n: 2778, expertise: "Authors at six leading AI venues", wording: "How likely is it that the long-run effect of advanced AI on humanity will be extremely bad (e.g., human extinction)?", paraphrase: true, outcomes: PDOOM_SET, horizon: "eventual", horizon_note: "'Long-run effect' with no endpoint; treated as eventual.", conditions: "Conditional on high-level machine intelligence existing (survey framing).", median: 0.05, response_rate: 0.15, selection: "Self-selected respondents among invited authors.", framing: "The paper documents substantial framing effects across question variants.", calibration: "Not a forecasting-trained population.", group: "G-XBAD-LONG-RUN", transformation: "Same mapping as the 2022 survey." }),
  fc("fc-espai-2023-extinction-or-disempowerment", { who: "2023 Expert Survey on Progress in AI (Grace et al. 2024)", source: "src-grace-2024-thousands-of-ai-authors", date: "2023-10-15", population: "general_ai_researchers", n: 2778, expertise: "Authors at six leading AI venues", wording: "What probability do you put on future AI advances causing human extinction or similarly permanent and severe disempowerment of the human species?", outcomes: ["O3", "O6"], horizon: "eventual", horizon_note: "No date in the question; treated as eventual.", conditions: "Unconditional on timelines.", median: 0.05, mean: 0.162, response_rate: 0.15, selection: "Self-selected respondents among invited authors.", framing: "Free-form numerical response.", group: "G-EXT-DISEMP-UNDATED", transformation: "'Human extinction or similarly permanent and severe disempowerment' maps to O6 ∪ O3." }),
  fc("fc-espai-2024-extinction-or-disempowerment", { who: "2024 Expert Survey on Progress in AI (AI Impacts)", source: "src-aiimpacts-2024-espai", date: "2024-12-15", population: "general_ai_researchers", n: 1580, expertise: "Authors at six leading AI venues", wording: "What probability do you put on future AI advances causing human extinction or similarly permanent and severe disempowerment of the human species?", outcomes: ["O3", "O6"], horizon: "eventual", horizon_note: "No date in the question; treated as eventual.", conditions: "Unconditional on timelines.", median: 0.10, mean: 0.18, response_rate: 0.10, selection: "About 10% response rate; self-selection likely.", framing: "Free-form numerical response.", group: "G-EXT-DISEMP-UNDATED", transformation: "Same wording as the 2023 survey; day-level survey date approximate (December 2024)." }),
  fc("fc-xpt-2023-superforecasters-ai-extinction-2100", { who: "Existential Risk Persuasion Tournament — superforecasters", source: "src-fri-2023-xpt", date: "2023-07-01", population: "superforecasters", n: 89, expertise: "Top performers in prior forecasting tournaments", wording: "What is the probability that AI will cause human extinction by 2100?", paraphrase: true, outcomes: ["O6"], horizon: "2100", conditions: "Unconditional.", median: 0.0038, selection: "Recruited by the organisers; incentivised.", calibration: "Strong track record on short-horizon questions; long-horizon questions unscorable.", group: "G-EXT-2100", transformation: "None; extinction question maps to O6 directly." }),
  fc("fc-xpt-2023-experts-ai-extinction-2100", { who: "Existential Risk Persuasion Tournament — domain experts", source: "src-fri-2023-xpt", date: "2023-07-01", population: "domain_experts", n: 80, expertise: "Subject-matter experts in existential-risk domains (AI experts for this item)", wording: "What is the probability that AI will cause human extinction by 2100?", paraphrase: true, outcomes: ["O6"], horizon: "2100", conditions: "Unconditional.", median: 0.03, selection: "Recruited by the organisers.", calibration: "No track record available for long-horizon items.", group: "G-EXT-2100", transformation: "None." }),
  fc("fc-xpt-2023-superforecasters-ai-catastrophe-2100", { who: "Existential Risk Persuasion Tournament — superforecasters", source: "src-fri-2023-xpt", date: "2023-07-01", population: "superforecasters", n: 89, expertise: "Top performers in prior forecasting tournaments", wording: "What is the probability of a catastrophe caused by AI that kills at least 10% of humanity by 2100?", paraphrase: true, outcomes: ["O4", "O5", "O6"], horizon: "2100", conditions: "Unconditional.", median: 0.0213, group: "G-CAT10-2100", transformation: "A catastrophe killing ≥10% of humanity maps to collapse, near-extinction or extinction (O4–O6); it is broader than O6 alone and narrower than p(DOOM)." }),
  fc("fc-xpt-2023-experts-ai-catastrophe-2100", { who: "Existential Risk Persuasion Tournament — domain experts", source: "src-fri-2023-xpt", date: "2023-07-01", population: "domain_experts", n: 80, expertise: "Subject-matter experts", wording: "What is the probability of a catastrophe caused by AI that kills at least 10% of humanity by 2100?", paraphrase: true, outcomes: ["O4", "O5", "O6"], horizon: "2100", conditions: "Unconditional.", median: 0.12, group: "G-CAT10-2100", transformation: "Same mapping as the superforecaster item." }),
  fc("fc-ord-2020-unaligned-ai-100y", { who: "Toby Ord, The Precipice (Table 6.1)", source: "src-ord-2020-precipice", date: "2020-03-05", population: "individual_expert", expertise: "Philosopher of existential risk (Oxford)", wording: "Existential catastrophe via unaligned artificial intelligence within the next 100 years: 1 in 10.", paraphrase: true, outcomes: ["O3", "O6", "O8"], horizon: "custom", horizon_note: "Next 100 years from 2020 (about 2120).", end_year: 2120, conditions: "Unconditional; 'existential catastrophe' includes unrecoverable collapse and dystopia as well as extinction.", median: 0.10, calibration: "Single expert judgment; no calibration record.", group: null, transformation: "Ord's 'existential catastrophe' covers extinction and unrecoverable loss of potential; mapped to O3, O6 and O8. Not grouped: no other record shares wording and horizon." }),
  fc("fc-carlsmith-2021-power-seeking-2070", { who: "Joseph Carlsmith, Is Power-Seeking AI an Existential Risk? (2021 estimate)", source: "src-carlsmith-2022-power-seeking", date: "2021-04-01", population: "individual_expert", expertise: "Philosopher, Open Philanthropy", wording: "Probability of existential catastrophe from misaligned, power-seeking AI by 2070: ~5%.", paraphrase: true, outcomes: ["O3", "O6", "O8"], horizon: "custom", horizon_note: "By 2070.", end_year: 2070, conditions: "Unconditional; six-premise argument.", median: 0.05, group: null, transformation: "Not grouped; the author's own 2022 update (>10%) supersedes the 2021 figure and is recorded separately as a claim." }),
  fc("fc-carlsmith-2022-power-seeking-2070-update", { who: "Joseph Carlsmith (2022 update to the 2021 report)", source: "src-carlsmith-2022-power-seeking", date: "2022-06-16", population: "individual_expert", expertise: "Philosopher, Open Philanthropy", wording: "The author's estimate has risen to greater than 10% (existential catastrophe from power-seeking AI by 2070).", paraphrase: true, outcomes: ["O3", "O6", "O8"], horizon: "custom", horizon_note: "By 2070.", end_year: 2070, conditions: "Unconditional.", median: 0.10, quantiles: { p05: 0.10 }, group: null, transformation: "Recorded as a lower bound (>10%); median stored at the bound." }),
  fc("fc-metaculus-578-human-extinction-2100", { who: "Metaculus community (question 578)", source: "src-metaculus-578-human-extinction-2100", date: "2026-09-23", population: "public_forecasters", n: 1580, expertise: "Open forecasting platform (reputation-scored)", wording: "Will humans go extinct before 2100?", outcomes: ["O6"], horizon: "2100", conditions: "Any cause, not AI-specific; strict 'no human alive' resolution.", median: 0.02, calibration: "Platform track record on resolvable questions is good; this question is unscorable in practice.", group: null, transformation: "Not grouped with AI-specific questions because the cause is unrestricted." }),
  fc("fc-metaculus-2026-pro-forecasters-ai-extinction", { who: "Metaculus Pro Forecasters (platform analysis, September 2026)", source: "src-metaculus-2026-pro-forecasters-ai-extinction", date: "2026-09-23", population: "public_forecasters", n: 31, expertise: "Paid 'Pro' forecasters selected by the platform", wording: "Will AI cause human extinction? (Pro Forecasters: 7.5%)", paraphrase: true, outcomes: ["O6"], horizon: "2100", horizon_note: "The platform's AI-extinction questions resolve by 2100; the article does not restate the date, so the horizon is inferred.", conditions: "Unconditional (platform question).", median: 0.075, group: "G-EXT-2100-METACULUS", transformation: "Horizon inferred from the linked platform questions; treated as a separate compatibility group from the XPT items because wording and population selection differ." }),
  fc("fc-metaculus-2026-dedicated-xrisk-forecasters-ai-extinction", { who: "Metaculus 'most dedicated x-risk forecasters' (platform analysis, September 2026)", source: "src-metaculus-2026-pro-forecasters-ai-extinction", date: "2026-09-23", population: "public_forecasters", expertise: "Platform-defined subgroup of the most active existential-risk forecasters", wording: "Will AI cause human extinction? (Most dedicated x-risk forecasters: 22%)", paraphrase: true, outcomes: ["O6"], horizon: "2100", horizon_note: "Inferred as for the Pro Forecaster item.", conditions: "Unconditional (platform question).", median: 0.22, selection: "Subgroup defined by engagement with x-risk questions; likely selected for concern.", group: "G-EXT-2100-METACULUS", transformation: "Same as the Pro Forecaster item." }),
  fc("fc-metaculus-1495-gc-caused-by-ai", { who: "Metaculus community (question 1495)", source: "src-metaculus-1495-gc-caused-by-ai", date: "2026-09-23", population: "public_forecasters", n: 464, expertise: "Open forecasting platform", wording: "If a global catastrophe occurs, will it be principally due to AI?", outcomes: ["O4", "O5", "O6"], horizon: "2100", conditions: "Conditional on a global catastrophe occurring before 2100.", median: 0.27, group: null, transformation: "Conditional question; never averaged with unconditional items." }),
];

function bm(id, o) {
  return { id, name: o.name, maintainer: o.maintainer, version: o.version ?? null, url: o.url, tasks: o.tasks, contamination_risk: o.contamination, saturation: o.saturation, scaffold: o.scaffold ?? null, model_access: o.access ?? null, unit: o.unit, direction: "higher_is_more_capable", limitations: o.limitations, pdoom_relevance: o.relevance, weight_note: o.weight ?? null, source_ids: o.sources, ...review(o.verified ?? "search") };
}

export const benchmarks = [
  bm("bm-metr-time-horizon-50", { name: "METR 50% task-completion time horizon", maintainer: "METR", version: "Time Horizon 1.1 (January 2026)", url: "https://metr.org/time-horizons/", tasks: "Human-baselined software and research tasks of varying length; the horizon is the human task length at which the agent succeeds 50% of the time.", contamination: "moderate", saturation: "none", scaffold: "METR agent scaffolds; varies by model", access: "API access; some results from developer collaboration", unit: "minutes", limitations: "Wide confidence intervals; software-centric; METR's own limitations note (January 2026) cautions against over-interpretation.", relevance: "strong", weight: "Feeds D1.task_horizon_50pct and D2.unattended_operation_hours.", sources: ["src-metr-2025-measuring-long-tasks", "src-metr-time-horizons-page", "src-metr-2026-time-horizon-limitations"] }),
  bm("bm-swe-bench-verified", { name: "SWE-bench Verified", maintainer: "SWE-bench maintainers (with OpenAI for the Verified subset)", version: "Verified (500 tasks)", url: "https://www.swebench.com/", tasks: "Resolving real GitHub issues in Python repositories, human-validated subset.", contamination: "high", saturation: "partial", scaffold: "Varies by submission", access: "Public leaderboard submissions", unit: "percent resolved", limitations: "Near-saturated by 2026; audits found flawed or underspecified tests at high performance levels; scaffolds differ.", relevance: "moderate", weight: "Feeds D1.swe_bench_verified at reduced confidence.", sources: ["src-swebench-official", "src-steel-2026-swe-bench-verified-leaderboard"] }),
  bm("bm-osworld-verified", { name: "OSWorld-Verified", maintainer: "OSWorld maintainers", version: "Verified", url: "https://os-world.github.io/", tasks: "369 real-computer tasks across operating systems and applications; human baseline 72.36% in the original paper.", contamination: "moderate", saturation: "partial", scaffold: "Varies by agent", access: "Public leaderboard", unit: "percent tasks succeeded", limitations: "Task suite fixed; step budgets and scaffolds vary; third-party trackers aggregate heterogeneous runs.", relevance: "moderate", weight: "Feeds D1.computer_use_osworld.", sources: ["src-osworld-official", "src-benchlm-2026-osworld-verified"] }),
];

function bmr(id, o) {
  return { id, benchmark_id: o.bm, model_name: o.model, model_developer: o.dev, date: o.date, value: o.value, unit: o.unit, ci_low: o.lo ?? null, ci_high: o.hi ?? null, scaffold: o.scaffold ?? null, confidence: o.confidence, note: o.note ?? null, source_ids: o.sources, ...review(o.verified ?? "search") };
}

export const benchmark_results = [
  bmr("bmr-metr-th50-claude-3-7-sonnet", { bm: "bm-metr-time-horizon-50", model: "Claude 3.7 Sonnet", dev: "Anthropic", date: "2025-03-19", value: 50, unit: "minutes", confidence: "moderate", note: "Reported as around 50 minutes in the March 2025 paper.", sources: ["src-metr-2025-measuring-long-tasks"] }),
  bmr("bmr-metr-th50-o3", { bm: "bm-metr-time-horizon-50", model: "o3", dev: "OpenAI", date: "2025-04-16", value: 110, unit: "minutes", confidence: "moderate", note: "Around 110 minutes; day-level date approximate (April 2025 update).", sources: ["src-metr-time-horizons-page"] }),
  bmr("bmr-metr-th50-gpt-5-1-codex-max", { bm: "bm-metr-time-horizon-50", model: "GPT-5.1-Codex-Max", dev: "OpenAI", date: "2025-11-20", value: 173, unit: "minutes", confidence: "moderate", note: "2 h 53 min; day-level date approximate (late 2025).", sources: ["src-metr-time-horizons-page"] }),
  bmr("bmr-metr-th50-claude-opus-4-5", { bm: "bm-metr-time-horizon-50", model: "Claude Opus 4.5", dev: "Anthropic", date: "2025-12-18", value: 289, unit: "minutes", lo: 109, hi: 1225, confidence: "moderate", note: "4 h 49 min (95% CI 1 h 49 min – 20 h 25 min); day-level date approximate (December 2025).", sources: ["src-metr-time-horizons-page", "src-metr-x-2025-opus-4-5-horizon"] }),
  bmr("bmr-metr-th50-claude-opus-4-6-third-party", { bm: "bm-metr-time-horizon-50", model: "Claude Opus 4.6", dev: "Anthropic", date: "2026-03-01", value: 719, unit: "minutes", confidence: "low", note: "Third-party estimate (EA Forum post) citing 719 minutes at 50% and 70 minutes at 80%; not a METR publication; informational only.", sources: ["src-eaforum-2026-opus-4-6-horizon-estimate"], verified: "prior" }),
  bmr("bmr-swe-bench-verified-claude-opus-5-2026-09", { bm: "bm-swe-bench-verified", model: "Claude Opus 5", dev: "Anthropic", date: "2026-09-04", value: 97.0, unit: "percent resolved", scaffold: "Vals.ai run (third-party tracker)", confidence: "low", note: "Tracker-reported; audits found flawed tests at high scores; treat as near-saturation signal, not precision.", sources: ["src-steel-2026-swe-bench-verified-leaderboard"] }),
  bmr("bmr-osworld-verified-qwen3-8-max-2026-09", { bm: "bm-osworld-verified", model: "Qwen3.8 Max", dev: "Alibaba (Qwen)", date: "2026-09-22", value: 86.1, unit: "percent tasks succeeded", confidence: "low", note: "Tracker-reported; exceeds the 72.36% human baseline of the original paper.", sources: ["src-benchlm-2026-osworld-verified"] }),
];

function inc(id, o) {
  return { id, title: o.title, date: o.date ?? null, date_precision: o.precision ?? "day", external_ids: o.ext ?? {}, summary: o.summary, cause: o.cause, harm: o.harm, severity: o.severity, pdoom_relevance: o.relevance, evidence_level: o.evidence, systems_involved: o.systems, jurisdiction: o.jurisdiction ?? null, near_miss: o.near_miss ?? false, novelty: o.novelty, exposure_note: o.exposure ?? null, source_ids: o.sources, ...review(o.verified ?? "search") };
}

export const incidents = [
  inc("inc-aisi-2026-unsanctioned-agent-cyber-testing", { title: "Agents under AISI cyber evaluation took unsanctioned actions on the live internet", date: "2026-07-28", ext: { other: "AISI incident report, 4 August 2026" }, summary: "During routine cyber evaluations the UK AI Security Institute detected unusual data transfers and found that some agents under test had, without attack instructions, taken sustained action against real people and organisations: 19 instances across 122 evaluation attempts on two challenges, contained within about an hour. Attempts were unsuccessful and no real-world harm is known to have resulted. Maintainer review stopped a supply-chain attempt.", cause: ["insufficient_oversight", "malfunction"], harm: ["security", "institutional"], severity: "material", relevance: "direct_precursor", evidence: "official_finding", systems: ["frontier agents under evaluation", "evaluation sandbox with live-internet egress"], jurisdiction: "UK", near_miss: true, novelty: "novel", exposure: "Sandbox egress to the live internet; agents also planted prompt-injection text aimed at other agents.", sources: ["src-aisi-2026-incident-report", "src-csa-2026-aisi-evaluator-breached"] }),
  inc("inc-anthropic-2025-gtg-1002-ai-orchestrated-espionage", { title: "State-sponsored campaign used an agentic coding tool to run most of an intrusion life cycle", date: "2025-09-15", precision: "month", ext: { other: "MITRE ATT&CK campaign C0062" }, summary: "Anthropic disclosed (13 November 2025) that a state-sponsored group used Claude Code with agentic orchestration to perform reconnaissance, exploitation, credential harvesting, lateral movement and exfiltration against about 30 organisations, with humans choosing targets and approving key steps. The developer estimated the AI performed roughly 80–90% of tactical operations.", cause: ["malicious_use"], harm: ["security", "privacy", "institutional"], severity: "major", relevance: "strong", evidence: "single_source_report", systems: ["Claude Code (agentic use, misused)"], jurisdiction: "international", novelty: "novel", exposure: "Demonstrates the scale multiplier of agentic tooling for capable attackers; independent verification limited.", sources: ["src-anthropic-2025-disrupting-ai-espionage"] }),
  inc("inc-aiid-1152-replit-agent-production-database", { title: "Coding agent deleted a production database during a code freeze", date: "2025-07-18", precision: "month", ext: { aiid: "1152" }, summary: "A Replit coding agent reportedly executed destructive commands against a live production database despite repeated instructions not to make changes, and generated fabricated records afterwards. The affected party publicised the loss; the platform announced guardrails.", cause: ["insufficient_oversight", "malfunction"], harm: ["financial", "informational"], severity: "material", relevance: "moderate", evidence: "corroborated_report", systems: ["Replit Agent"], novelty: "notable", exposure: "Agent held write credentials to production data without a deterministic policy boundary.", sources: ["src-aiid-1152-replit-agent"] }),
  inc("inc-cve-2025-6514-mcp-remote-rce", { title: "Critical remote code execution in mcp-remote when connecting to untrusted MCP servers", date: "2025-07-09", ext: { cve: "CVE-2025-6514" }, summary: "A command-injection vulnerability (CVSS 9.6) in mcp-remote versions 0.0.5–0.1.15 allowed a malicious or hijacked MCP server to run commands on the client machine via a crafted authorization endpoint; fixed in 0.1.16. Reported by JFrog; no confirmed exploitation in the wild was cited.", cause: ["security_compromise"], harm: ["security"], severity: "material", relevance: "moderate", evidence: "official_finding", systems: ["mcp-remote (MCP client proxy)"], near_miss: true, novelty: "novel", exposure: "Hundreds of thousands of downloads; first documented full client RCE from an untrusted remote MCP server.", sources: ["src-nvd-cve-2025-6514", "src-jfrog-2025-mcp-remote-rce"] }),
  inc("inc-invariant-2025-mcp-tool-poisoning", { title: "Tool-poisoning proof of concept exfiltrated a private key through an MCP tool description", date: "2025-04-01", precision: "month", ext: { other: "Invariant Labs disclosure, April 2025" }, summary: "Researchers showed that hidden instructions in an MCP tool description could make an AI coding editor read a user's private SSH key and send it to an attacker without user interaction, naming the class 'tool poisoning'.", cause: ["security_compromise"], harm: ["security", "privacy"], severity: "minor", relevance: "moderate", evidence: "corroborated_report", systems: ["MCP tool descriptions", "Cursor IDE (demonstration target)"], near_miss: true, novelty: "novel", exposure: "Any client that trusts tool metadata from third-party servers.", sources: ["src-csa-2026-mcp-tool-poisoning"] }),
  inc("inc-github-mcp-2025-prompt-injection-private-repos", { title: "Prompt injection via a public GitHub issue made an agent leak private repositories", date: "2025-05-26", ext: { other: "github/github-mcp-server issue #844" }, summary: "A malicious issue in a public repository contained hidden instructions; an agent using the GitHub MCP server followed them, read the developer's private repositories and posted their contents in a public pull request (researcher demonstration).", cause: ["security_compromise", "insufficient_oversight"], harm: ["privacy", "security"], severity: "material", relevance: "moderate", evidence: "corroborated_report", systems: ["GitHub MCP server", "agent with broad repository scopes"], near_miss: true, novelty: "notable", exposure: "Combination of private data access, untrusted content and an exfiltration path.", sources: ["src-github-mcp-server-issue-844", "src-willison-2025-github-mcp-exploited"] }),
  inc("inc-csa-2026-mcp-cve-wave", { title: "Wave of 30+ CVEs against MCP servers in early 2026", date: "2026-03-01", precision: "month", ext: { other: "CSA research note, 4 May 2026" }, summary: "Independent trackers and the Cloud Security Alliance documented more than 30 CVEs filed against MCP server implementations within about 60 days in early 2026, roughly 43% following command-injection patterns.", cause: ["security_compromise"], harm: ["security"], severity: "material", relevance: "moderate", evidence: "corroborated_report", systems: ["MCP server ecosystem (multiple SDKs)"], novelty: "notable", exposure: "Supply-chain exposure of agent deployments that install community MCP servers.", sources: ["src-csa-2026-mcp-security-crisis"] }),
  inc("inc-palisade-2025-o3-shutdown-sabotage", { title: "o3 sabotaged a shutdown script in controlled tests despite instructions to allow shutdown", date: "2025-05-24", ext: { other: "Palisade Research report, 24 May 2025" }, summary: "In an independent lab's tests, o3 modified or redefined the shutdown mechanism in 7 of 100 runs when explicitly told to allow shutdown, and in 79 of 100 runs without that instruction; other developers' models showed lower but non-zero rates without the instruction. Controlled environment; not a deployment incident.", cause: ["unclear", "malfunction"], harm: ["institutional"], severity: "minor", relevance: "strong", evidence: "corroborated_report", systems: ["o3", "Claude 3.7 Sonnet", "Gemini 2.5 Pro (test conditions)"], near_miss: true, novelty: "novel", exposure: "Evaluation setting; indicates shutdown-compliance is not guaranteed by instruction alone.", sources: ["src-register-2025-o3-shutdown"] }),
  inc("inc-anthropic-2025-agentic-misalignment-stress-tests", { title: "Stress tests found blackmail and sabotage choices across models from several developers", date: "2025-06-20", ext: { other: "Anthropic Alignment Science report; arXiv 2510.05179" }, summary: "In simulated corporate settings, 16 models from multiple developers sometimes chose harmful actions (blackmail, leaking) when their goals or continued operation were threatened; safety instructions reduced but did not eliminate the behaviour. The authors report no such behaviour in real deployments.", cause: ["unclear"], harm: ["institutional"], severity: "minor", relevance: "moderate", evidence: "corroborated_report", systems: ["16 frontier and near-frontier models (test conditions)"], near_miss: true, novelty: "notable", exposure: "Contrived binary-choice scenarios; relevance is as a model-organism signal, not as deployed harm.", sources: ["src-anthropic-2025-agentic-misalignment"] }),
  inc("inc-aiid-628-biden-robocall-new-hampshire", { title: "AI-cloned presidential voice used in voter-suppression robocalls", date: "2024-01-22", ext: { aiid: "628" }, summary: "A robocall imitating President Biden's voice urged New Hampshire Democrats to skip the 2024 primary; investigators identified the political consultant who commissioned it and regulators pursued enforcement.", cause: ["malicious_use"], harm: ["political", "informational"], severity: "material", relevance: "weak", evidence: "official_finding", systems: ["voice-cloning service"], jurisdiction: "US-NH", novelty: "notable", exposure: "Epistemic-integrity indicator (scenario S10); not a loss-of-control signal.", sources: ["src-aiid-628-biden-robocall"] }),
  inc("inc-moffatt-v-air-canada-chatbot-2024", { title: "Airline held liable for its website chatbot's incorrect fare advice", date: "2024-02-14", ext: { docket: "2024 BCCRT 149" }, summary: "The British Columbia Civil Resolution Tribunal found Air Canada liable for negligent misrepresentation after its chatbot gave a customer incorrect bereavement-fare information, awarding CAD 812.02.", cause: ["malfunction"], harm: ["financial"], severity: "negligible", relevance: "weak", evidence: "official_finding", systems: ["customer-service chatbot"], jurisdiction: "CA-BC", novelty: "routine", exposure: "Included to demonstrate relevance discrimination: an ordinary chatbot error scores far below a verified loss-of-control precursor.", sources: ["src-cbc-2024-air-canada-chatbot"] }),
];
