// Copyright NU Cybernetics. p(DOOM) — research prototype.
import { review } from "./helpers.mjs";

function iv(id, o) {
  return {
    id, name: o.name, target_scenario_ids: o.targets, mechanism: o.mechanism, evidence_summary: o.evidence,
    evidence_strength: o.strength, cost: o.cost, time_to_deploy: o.time, effect_size: "unknown", uncertainty: o.uncertainty ?? "high",
    possible_failure: o.failure, possible_backfire: o.backfire, owner_types: o.owners, user_actions: o.actions,
    category: o.category, source_ids: o.sources ?? [], ...review(o.verified ?? "search", "informational"),
  };
}

export const interventions = [
  iv("I01", { name: "Better dangerous-capability evaluations", targets: ["S1", "S2", "S4", "S6", "S14"], mechanism: "Measure cyber, biological, autonomy and deception capabilities before and during deployment so thresholds trigger safeguards.", evidence: "Developer frameworks (Anthropic RSP, OpenAI Preparedness v2, DeepMind FSF v3) and government evaluators (UK AISI, US CAISI) run such evaluations; the 2026 International AI Safety Report documents both progress and evidence gaps.", strength: "moderate", cost: "moderate", time: "months", failure: "Evaluation awareness and sandbagging by models; benchmarks saturate or leak.", backfire: "False reassurance from passed evaluations; publication of evaluation details aiding misuse.", owners: ["laboratories", "governments", "third-party evaluators"], actions: [{ audience: "ai_researchers", action: "Build and replicate evaluations for strategic behaviour." }, { audience: "policymakers", action: "Fund independent evaluation capacity." }], category: "technical", sources: ["src-anthropic-rsp", "src-openai-preparedness-v2", "src-gdm-fsf-v3", "src-aisi-inspect", "src-iasr-2026"] }),
  iv("I02", { name: "Third-party audits", targets: ["S15", "S14", "S1"], mechanism: "Independent parties verify safety claims, evaluations and security practices rather than relying on self-reports.", evidence: "Emerging practice; SB 53 and the EU AI Act create disclosure duties that audits can verify.", strength: "weak", cost: "moderate", time: "1-2y", failure: "Auditor capture or lack of model access.", backfire: "Audit theatre substituting for substantive change.", owners: ["laboratories", "auditors", "regulators"], actions: [{ audience: "laboratories", action: "Grant pre-deployment access to independent evaluators." }], category: "organizational", sources: ["src-ca-sb53-tfaia", "src-eu-ai-act-gpai-guidelines"] }),
  iv("I03", { name: "Mandatory incident reporting", targets: ["S15", "S3", "S4"], mechanism: "Require developers and deployers to report serious incidents so regulators and the public learn quickly.", evidence: "EU AI Act obligations for general-purpose models with systemic risk (from August 2025) and California SB 53 critical-safety-incident reporting (from 2026).", strength: "moderate", cost: "low", time: "months", failure: "Under-reporting; vague thresholds.", backfire: "Chilling of internal red-teaming if reports are punitive.", owners: ["policymakers", "regulators"], actions: [{ audience: "policymakers", action: "Harmonise incident definitions with the OECD framework." }], category: "national", sources: ["src-eu-ai-act-gpai-guidelines", "src-ca-sb53-tfaia", "src-oecd-2024-defining-ai-incidents"] }),
  iv("I04", { name: "Strong model-weight security", targets: ["S4", "S6", "S15"], mechanism: "Protect weights from theft so dangerous capabilities do not diffuse to actors outside safeguards.", evidence: "RAND's 2024 security levels SL1–SL5; the report found no company at SL3 at the time.", strength: "moderate", cost: "high", time: "1-2y", failure: "Insider threat; state-level attackers.", backfire: "Concentration of power in a few secured actors.", owners: ["laboratories", "governments"], actions: [{ audience: "laboratories", action: "Publish the security level achieved and audit it." }], category: "technical", sources: ["src-rand-2024-securing-model-weights"] }),
  iv("I05", { name: "Compute monitoring", targets: ["S14", "S15", "S4"], mechanism: "Track large training runs and compute access to give governance visibility and leverage.", evidence: "Analysis of compute as a governance lever; Epoch data on 4–5× yearly growth of frontier training compute.", strength: "weak", cost: "moderate", time: "1-2y", failure: "Algorithmic efficiency reduces the compute signal.", backfire: "Surveillance overreach; incentive to hide runs.", owners: ["governments", "cloud providers"], actions: [{ audience: "policymakers", action: "Require reporting thresholds for large training runs." }], category: "international", sources: ["src-sastry-2024-computing-power-governance", "src-epoch-2024-compute-growth"] }),
  iv("I06", { name: "Sandboxing", targets: ["S1", "S3", "S5"], mechanism: "Isolate agents from production systems and the live internet during evaluation and risky operation.", evidence: "The 2026 AISI incident showed that sandbox egress to the live internet is a real gap; NSA guidance calls for least-privilege agent processes.", strength: "moderate", cost: "moderate", time: "months", failure: "Egress misconfiguration; sandbox escapes.", backfire: "False confidence in imperfect isolation.", owners: ["laboratories", "software engineers", "evaluators"], actions: [{ audience: "software_engineers", action: "Default-deny egress for agent sandboxes." }], category: "technical", sources: ["src-aisi-2026-incident-report", "src-nsa-2026-mcp-security"] }),
  iv("I07", { name: "Least-privilege tool access", targets: ["S3", "S5", "S1"], mechanism: "Grant agents only the tools, scopes and credentials a task needs.", evidence: "The GitHub MCP prompt-injection demonstration and the Replit data loss both involved over-broad scopes; NSA and OWASP guidance recommend least privilege.", strength: "moderate", cost: "low", time: "months", failure: "Scope creep for convenience.", backfire: "None significant.", owners: ["software engineers", "platform vendors"], actions: [{ audience: "software_engineers", action: "Scope tokens per task; never give agents production write access by default." }], category: "technical", sources: ["src-github-mcp-server-issue-844", "src-aiid-1152-replit-agent", "src-nsa-2026-mcp-security", "src-owasp-genai-security"] }),
  iv("I08", { name: "Deterministic agent policies", targets: ["S2", "S3", "S11", "S13"], mechanism: "Enforce allow/deny rules, budgets and rate limits in code outside the model so instructions in content cannot override them.", evidence: "Tool-poisoning and prompt-injection incidents show that model-level instructions are insufficient; deterministic enforcement is standard security practice.", strength: "moderate", cost: "low", time: "months", failure: "Policies too coarse to be useful.", backfire: "None significant.", owners: ["software engineers"], actions: [{ audience: "software_engineers", action: "Put policy checks in the harness, not the prompt." }], category: "technical", sources: ["src-csa-2026-mcp-tool-poisoning", "src-thn-2026-microsoft-mcp-tool-descriptions"] }),
  iv("I09", { name: "Human approval for high-impact actions", targets: ["S1", "S2", "S3", "S8"], mechanism: "Require explicit human confirmation before irreversible or high-value actions.", evidence: "Would have prevented the Replit deletion; widely recommended in agent security guidance.", strength: "moderate", cost: "low", time: "months", failure: "Approval fatigue; rubber-stamping.", backfire: "Slower operations pushing users to disable it.", owners: ["software engineers", "deployers"], actions: [{ audience: "software_engineers", action: "Classify actions by impact and gate the irreversible ones." }], category: "technical", sources: ["src-aiid-1152-replit-agent", "src-owasp-genai-security"] }),
  iv("I10", { name: "Agent cancellation", targets: ["S3", "S13"], mechanism: "Guarantee that running agents and their delegates can be stopped and their effects rolled back.", evidence: "AISI contained its incident within about an hour of discovery, showing the value of stop paths; nested delegation complicates propagation.", strength: "weak", cost: "moderate", time: "months", failure: "Cancellation not propagated to sub-agents.", backfire: "None significant.", owners: ["software engineers", "platform vendors"], actions: [{ audience: "software_engineers", action: "Propagate cancellation tokens through every delegation." }], category: "technical", sources: ["src-aisi-2026-incident-report"] }),
  iv("I11", { name: "Secure MCP registries", targets: ["S3", "S12", "S13"], mechanism: "Verify server identity and metadata, monitor tool-list changes and scan server code before agents connect.", evidence: "The official MCP Registry (preview since September 2025) provides namespace verification but relies on the ecosystem for code scanning; NSA guidance treats tool-list changes as security events.", strength: "weak", cost: "moderate", time: "1-2y", failure: "Registry provides identity but not behaviour guarantees.", backfire: "Centralisation risk.", owners: ["standards bodies", "platform vendors"], actions: [{ audience: "standards_bodies", action: "Add signing and provenance requirements to registry entries." }], category: "technical", sources: ["src-mcp-registry-about", "src-nsa-2026-mcp-security", "src-csa-2026-mcp-security-crisis"] }),
  iv("I12", { name: "Signed skills and dependencies", targets: ["S12", "S3"], mechanism: "Cryptographically sign agent skills, plugins and dependencies so tampering is detectable.", evidence: "Supply-chain compromise of agent tooling is documented (mcp-remote RCE; 2026 CVE wave); signing is established practice in package ecosystems.", strength: "weak", cost: "moderate", time: "1-2y", failure: "Keys compromised; unsigned long tail.", backfire: "None significant.", owners: ["software engineers", "standards bodies"], actions: [{ audience: "software_engineers", action: "Pin and verify every skill and server dependency." }], category: "technical", sources: ["src-nvd-cve-2025-6514", "src-csa-2026-mcp-security-crisis"] }),
  iv("I13", { name: "Model organisms of misalignment", targets: ["S1"], mechanism: "Deliberately create and study misaligned behaviours in controlled models to develop detection and mitigation.", evidence: "Alignment-faking (2024) and agentic-misalignment (2025) studies are the main examples.", strength: "moderate", cost: "moderate", time: "months", failure: "Organisms not representative of natural misalignment.", backfire: "Information hazards if methods aid misuse.", owners: ["ai researchers", "laboratories"], actions: [{ audience: "ai_researchers", action: "Replicate and stress-test published model organisms." }], category: "technical", sources: ["src-anthropic-2024-alignment-faking", "src-anthropic-2025-agentic-misalignment"] }),
  iv("I14", { name: "Interpretability", targets: ["S1", "S17"], mechanism: "Understand model internals well enough to detect deception and goal divergence.", evidence: "Active research area; no deployed detector for strategic deception exists.", strength: "weak", cost: "high", time: "3-5y", failure: "Does not scale to frontier models.", backfire: "Over-trust in partial explanations.", owners: ["ai researchers", "laboratories"], actions: [{ audience: "ai_researchers", action: "Work on detection of deceptive cognition." }], category: "technical", sources: ["src-iasr-2026"] }),
  iv("I15", { name: "Scalable oversight", targets: ["S1", "S2", "S17"], mechanism: "Methods that let humans supervise systems more capable than themselves.", evidence: "Research programme; empirical results limited to modest capability gaps.", strength: "weak", cost: "high", time: "3-5y", failure: "Oversight collapses at large capability gaps.", backfire: "None significant.", owners: ["ai researchers"], actions: [{ audience: "ai_researchers", action: "Test oversight protocols at increasing capability gaps." }], category: "technical", sources: ["src-iasr-2026"] }),
  iv("I16", { name: "Control evaluations", targets: ["S1", "S3", "S13"], mechanism: "Test whether deployment protocols remain safe even if the model actively tries to subvert them.", evidence: "Redwood Research's control framework (2023) and lab adoption; scaling to frontier deployments is unproven.", strength: "moderate", cost: "moderate", time: "1-2y", failure: "Red teams weaker than real models.", backfire: "None significant.", owners: ["laboratories", "ai researchers"], actions: [{ audience: "laboratories", action: "Publish control evaluations for agentic deployments." }], category: "technical", sources: ["src-greenblatt-2023-ai-control"] }),
  iv("I17", { name: "International coordination", targets: ["S4", "S6", "S7", "S8", "S9", "S10", "S11", "S14", "S15", "S16", "S17"], mechanism: "Shared thresholds, reporting and verification across jurisdictions reduce race incentives.", evidence: "International AI Safety Report process; binding rules so far national (EU, California, New York, Korea).", strength: "weak", cost: "high", time: "3-5y", failure: "Geopolitical competition blocks agreement.", backfire: "Lowest-common-denominator standards.", owners: ["governments", "international bodies"], actions: [{ audience: "policymakers", action: "Support interoperable incident and evaluation standards." }], category: "international", sources: ["src-iasr-2026", "src-eu-ai-act-gpai-guidelines", "src-bengio-2024-science-managing-extreme-risks"] }),
  iv("I18", { name: "Whistleblower protections", targets: ["S15", "S9"], mechanism: "Protect insiders who report safety failures so problems surface before harm.", evidence: "California SB 53 includes whistleblower protections for frontier developers' employees.", strength: "moderate", cost: "low", time: "months", failure: "Weak enforcement.", backfire: "None significant.", owners: ["policymakers", "laboratories"], actions: [{ audience: "policymakers", action: "Extend protections to contractors and evaluators." }], category: "national", sources: ["src-ca-sb53-tfaia"] }),
  iv("I19", { name: "Safety cases", targets: ["S1", "S3"], mechanism: "Structured, reviewable arguments that a system is safe to deploy, tied to evidence.", evidence: "Framework literature (2024); early adoption in developer frameworks.", strength: "weak", cost: "moderate", time: "1-2y", failure: "Arguments unfalsifiable or unreviewed.", backfire: "Paperwork substituting for evidence.", owners: ["laboratories", "regulators"], actions: [{ audience: "laboratories", action: "Publish safety cases for each frontier deployment." }], category: "organizational", sources: ["src-clymer-2024-safety-cases"] }),
  iv("I20", { name: "Staged deployment", targets: ["S2", "S4", "S6", "S14"], mechanism: "Release capabilities gradually with monitoring and rollback at each stage.", evidence: "Standard practice in developer frameworks; effectiveness depends on monitoring quality.", strength: "moderate", cost: "low", time: "months", failure: "Stages skipped under competitive pressure.", backfire: "None significant.", owners: ["laboratories"], actions: [{ audience: "laboratories", action: "Preserve rollback for every stage." }], category: "organizational", sources: ["src-anthropic-rsp", "src-openai-preparedness-v2"] }),
  iv("I21", { name: "Emergency response", targets: ["S3", "S4", "S5", "S6", "S7"], mechanism: "Prepared institutions and drills for AI-related incidents across sectors.", evidence: "The 2026 International AI Safety Report calls for broader societal resilience including incident-response protocols; AISI's rapid containment is an example.", strength: "weak", cost: "moderate", time: "1-2y", failure: "Plans untested.", backfire: "None significant.", owners: ["governments", "operators"], actions: [{ audience: "policymakers", action: "Run cross-sector AI incident exercises." }], category: "resilience", sources: ["src-iasr-2026", "src-aisi-2026-incident-report"] }),
  iv("I22", { name: "Liability and insurance", targets: ["S8", "S15"], mechanism: "Make developers and deployers bear costs of harm so safety is priced in.", evidence: "Tribunal decisions (e.g., Moffatt v. Air Canada) establish liability for chatbot outputs; frontier-specific regimes are nascent.", strength: "weak", cost: "low", time: "1-2y", failure: "Catastrophic harms exceed insurable limits.", backfire: "Liability shields negotiated into law.", owners: ["policymakers", "insurers"], actions: [{ audience: "policymakers", action: "Clarify liability for autonomous agent actions." }], category: "national", sources: ["src-cbc-2024-air-canada-chatbot"] }),
  iv("I23", { name: "Public-interest laboratories", targets: ["S9", "S15", "S16"], mechanism: "Capability development outside purely commercial incentives, with safety and transparency mandates.", evidence: "Government institutes (UK AISI, US CAISI) provide evaluation capacity; public-interest development remains limited.", strength: "weak", cost: "very_high", time: "3-5y", failure: "Under-funding relative to frontier labs.", backfire: "Adds another racing actor.", owners: ["governments", "funders"], actions: [{ audience: "funders", action: "Fund independent evaluation and safety infrastructure." }], category: "national", sources: ["src-aisi-inspect", "src-ssti-2025-caisi-rename"] }),
  iv("I24", { name: "Nonprofit alignment research", targets: ["S1", "S2"], mechanism: "Independent research on alignment, control and evaluation free from deployment pressure.", evidence: "Organisations such as METR, Redwood Research and Apollo Research produce widely used evaluations.", strength: "moderate", cost: "moderate", time: "1-2y", failure: "Talent and compute gaps versus labs.", backfire: "None significant.", owners: ["funders", "nonprofits"], actions: [{ audience: "funders", action: "Support multi-year independent research." }], category: "organizational", sources: ["src-metr-2025-measuring-long-tasks", "src-greenblatt-2023-ai-control"] }),
  iv("I25", { name: "Open safety tooling", targets: ["S9", "S10", "S12"], mechanism: "Open-source evaluation, monitoring and provenance tools so safeguards are widely available.", evidence: "UK AISI's Inspect (MIT licence) lists 171 evaluations by September 2026.", strength: "moderate", cost: "low", time: "months", failure: "Maintenance burden.", backfire: "Evaluation details aid gaming.", owners: ["governments", "nonprofits", "software engineers"], actions: [{ audience: "software_engineers", action: "Contribute evaluations and security tooling." }], category: "technical", sources: ["src-aisi-inspect"] }),
  iv("I26", { name: "Forecasting", targets: ["S7", "S16", "S18"], mechanism: "Structured forecasting on resolvable proxies improves anticipation and calibration.", evidence: "XPT and Metaculus provide track records on short-horizon questions; long-horizon questions cannot be scored.", strength: "weak", cost: "low", time: "months", failure: "Unresolvable questions; incentive problems.", backfire: "False precision.", owners: ["nonprofits", "researchers"], actions: [{ audience: "individuals", action: "Participate in resolvable proxy forecasts." }], category: "organizational", sources: ["src-fri-2023-xpt", "src-metaculus-578-human-extinction-2100"] }),
  iv("I27", { name: "Resilience engineering", targets: ["S2", "S5", "S8", "S10", "S11", "S12", "S16", "S18"], mechanism: "Manual fallbacks, segmentation, redundancy and recovery capacity that limit the damage of any single failure.", evidence: "Recommended by the 2026 International AI Safety Report; evidence of effectiveness is thin.", strength: "weak", cost: "high", time: "3-5y", failure: "Cost pressure erodes redundancy.", backfire: "None significant.", owners: ["operators", "governments"], actions: [{ audience: "policymakers", action: "Require manual fallback for critical services." }], category: "resilience", sources: ["src-iasr-2026"] }),
];

function org(id, o) {
  return { id, name: o.name, url: o.url, mission: o.mission, legal_status: o.legal, jurisdiction: o.jurisdiction, focus: o.focus, programs: o.programs, open_outputs: o.outputs, funding_disclosure: o.funding, conflicts: o.conflicts ?? [], evidence_of_impact: o.impact, ways_to_help: o.help, inclusion_criteria_met: o.criteria ?? ["independent_or_public_interest", "public_documented_outputs", "verifiable_website"], last_verified: "2026-09-26", source_ids: o.sources ?? [], ...review(o.verified ?? "prior", "informational") };
}

export const organizations = [
  org("org-metr", { name: "METR", url: "https://metr.org/", mission: "Evaluate whether frontier AI systems pose catastrophic risks, with a focus on autonomous capabilities.", legal: "US 501(c)(3) nonprofit (as stated by the organisation)", jurisdiction: "US", focus: ["evaluations", "autonomy", "time_horizon"], programs: ["Time-horizon measurement", "Pre-deployment evaluations with developers", "Task standard"], outputs: ["Measuring AI Ability to Complete Long Tasks (2025)", "Time Horizon 1.1 (2026)", "Public task standard"], funding: "Publishes funder information on its website; receives philanthropic funding.", impact: "Time-horizon metric adopted in the International AI Safety Report and widely cited.", help: ["Donate", "Join as researcher or engineer", "Contribute tasks"], sources: ["src-metr-2025-measuring-long-tasks", "src-metr-time-horizons-page"], verified: "search" }),
  org("org-epoch-ai", { name: "Epoch AI", url: "https://epoch.ai/", mission: "Research the trajectory of AI through data on compute, models and benchmarks.", legal: "Research institute (nonprofit project)", jurisdiction: "US", focus: ["compute", "trends", "benchmarks"], programs: ["Trends dashboards", "Benchmarking hub"], outputs: ["Training compute growth analyses", "Public datasets"], funding: "Philanthropic; disclosed on website.", impact: "Data widely used by governments and researchers.", help: ["Use and cite data", "Report corrections"], sources: ["src-epoch-2024-compute-growth"], verified: "search" }),
  org("org-forecasting-research-institute", { name: "Forecasting Research Institute", url: "https://forecastingresearch.org/", mission: "Advance the science of forecasting for high-stakes decisions.", legal: "US nonprofit", jurisdiction: "US", focus: ["forecasting", "existential_risk"], programs: ["Existential Risk Persuasion Tournament", "Near-term accuracy studies"], outputs: ["XPT report (2023)", "Roots of Disagreement on AI Risk"], funding: "Philanthropic; disclosed on website.", impact: "XPT is the reference dataset for superforecaster versus expert disagreement on AI risk.", help: ["Participate in studies", "Donate"], sources: ["src-fri-2023-xpt"], verified: "search" }),
  org("org-ai-impacts", { name: "AI Impacts", url: "https://aiimpacts.org/", mission: "Research questions relevant to the future of AI, including expert surveys.", legal: "Nonprofit research project", jurisdiction: "US", focus: ["expert_surveys", "timelines"], programs: ["Expert Survey on Progress in AI (2016, 2022, 2023, 2024)"], outputs: ["ESPAI datasets and reports"], funding: "Philanthropic; disclosed on website.", impact: "Largest recurring surveys of AI researchers on risk and timelines.", help: ["Cite carefully with wording", "Donate"], sources: ["src-aiimpacts-2022-espai", "src-aiimpacts-2024-espai"], verified: "search" }),
  org("org-uk-ai-security-institute", { name: "UK AI Security Institute", url: "https://www.aisi.gov.uk/", mission: "Government research body evaluating and mitigating risks from advanced AI.", legal: "UK government body (Department for Science, Innovation and Technology)", jurisdiction: "UK", focus: ["evaluations", "cyber", "open_tooling"], programs: ["Inspect framework", "Pre-deployment testing", "Incident reporting"], outputs: ["Inspect (MIT)", "Inspect Evals register", "2026 incident report"], funding: "UK Government.", conflicts: ["government_policy_context"], impact: "Open evaluation framework adopted widely; secretariat for the International AI Safety Report.", help: ["Contribute evaluations to Inspect", "Apply for roles"], criteria: ["public_body", "public_documented_outputs", "verifiable_website"], sources: ["src-aisi-inspect", "src-aisi-2026-incident-report"], verified: "search" }),
  org("org-cloud-security-alliance", { name: "Cloud Security Alliance", url: "https://cloudsecurityalliance.org/", mission: "Define and raise awareness of best practices for secure cloud and AI computing.", legal: "US 501(c)(6) nonprofit (as stated)", jurisdiction: "US", focus: ["security", "agents", "mcp"], programs: ["Lab Space research notes", "AI Safety Initiative"], outputs: ["MCP security research notes (2026)"], funding: "Membership and sponsorship; corporate members.", conflicts: ["commercial_interest"], impact: "Timely analyses of agent-infrastructure incidents.", help: ["Join working groups"], sources: ["src-csa-2026-mcp-security-crisis"], verified: "search" }),
  org("org-institute-for-ai-policy-and-strategy", { name: "Institute for AI Policy and Strategy", url: "https://www.iaps.ai/", mission: "Research and policy on frontier AI, compute governance and security.", legal: "Nonprofit think tank", jurisdiction: "US", focus: ["governance", "security"], programs: ["Autonomous cyber attacks analysis", "Compute governance"], outputs: ["The Emergence of Autonomous Cyber Attacks (2025)"], funding: "Philanthropic; disclosed on website.", impact: "Policy analyses cited in governance debates.", help: ["Read and engage with research"], verified: "search" }),
  org("org-ada-lovelace-institute", { name: "Ada Lovelace Institute", url: "https://www.adalovelaceinstitute.org/", mission: "Ensure data and AI work for people and society.", legal: "UK independent research institute (Nuffield Foundation)", jurisdiction: "UK", focus: ["governance", "accountability"], programs: ["Analysis of AI institutions including AISI"], outputs: ["Making sense of the UK's AI Security Institute"], funding: "Nuffield Foundation and grants; disclosed.", impact: "Influential UK policy analysis.", help: ["Engage with consultations"], verified: "search" }),
  org("org-apollo-research", { name: "Apollo Research", url: "https://www.apolloresearch.ai/", mission: "Evaluate frontier models for deceptive and scheming behaviour.", legal: "Nonprofit research organisation", jurisdiction: "UK", focus: ["evaluations", "deception"], programs: ["Scheming evaluations", "Pre-deployment testing with developers"], outputs: ["Published evaluation reports"], funding: "Philanthropic; disclosed on website.", impact: "Evaluations cited in developer system cards.", help: ["Apply for roles", "Donate"] }),
  org("org-redwood-research", { name: "Redwood Research", url: "https://www.redwoodresearch.org/", mission: "Research on AI control and alignment.", legal: "US nonprofit", jurisdiction: "US", focus: ["control", "alignment"], programs: ["AI control evaluations"], outputs: ["AI Control: Improving Safety Despite Intentional Subversion (2023)"], funding: "Philanthropic; disclosed on website.", impact: "Originated the control-evaluation framework.", help: ["Collaborate on control research"], sources: ["src-greenblatt-2023-ai-control"] }),
  org("org-center-for-ai-safety", { name: "Center for AI Safety", url: "https://www.safe.ai/", mission: "Reduce societal-scale risks from AI through research, field-building and advocacy.", legal: "US 501(c)(3) nonprofit", jurisdiction: "US", focus: ["research", "advocacy", "taxonomy"], programs: ["Research", "Compute cluster for safety research", "Policy"], outputs: ["An Overview of Catastrophic AI Risks (2023)"], funding: "Philanthropic; disclosed on website.", conflicts: ["advocacy_context"], impact: "Widely cited taxonomy; convened the 2023 statement on AI risk.", help: ["Donate", "Research collaborations"], sources: ["src-hendrycks-2023-overview-catastrophic-risks"] }),
  org("org-centre-for-the-governance-of-ai", { name: "Centre for the Governance of AI", url: "https://www.governance.ai/", mission: "Research how humanity can navigate the transition to advanced AI.", legal: "UK nonprofit", jurisdiction: "UK", focus: ["governance", "compute"], programs: ["Research fellowships"], outputs: ["Computing Power and the Governance of AI (2024, co-authored)"], funding: "Philanthropic; disclosed on website.", impact: "Governance research cited by policymakers.", help: ["Fellowships", "Donate"], sources: ["src-sastry-2024-computing-power-governance"] }),
  org("org-centre-for-long-term-resilience", { name: "Centre for Long-Term Resilience", url: "https://www.longtermresilience.org/", mission: "Transform global resilience to extreme risks including AI and biosecurity.", legal: "UK think tank", jurisdiction: "UK", focus: ["resilience", "biosecurity", "governance"], programs: ["Policy research", "Government engagement"], outputs: ["Policy reports"], funding: "Philanthropic; disclosed on website.", impact: "Engaged in UK resilience policy.", help: ["Engage with reports"] }),
  org("org-cset", { name: "Center for Security and Emerging Technology", url: "https://cset.georgetown.edu/", mission: "Policy research on security implications of emerging technologies.", legal: "University research centre (Georgetown)", jurisdiction: "US", focus: ["governance", "security", "compute"], programs: ["Data and analysis", "Policy briefs"], outputs: ["Reports and datasets"], funding: "Philanthropic and university; disclosed.", impact: "Widely used by US policymakers.", help: ["Use data", "Engage with briefs"] }),
  org("org-far-ai", { name: "FAR.AI", url: "https://far.ai/", mission: "Incubate and accelerate research on AI safety and alignment.", legal: "US nonprofit", jurisdiction: "US", focus: ["alignment", "robustness"], programs: ["Research", "Events"], outputs: ["Adversarial robustness research"], funding: "Philanthropic; disclosed on website.", impact: "Research and convening.", help: ["Apply", "Donate"] }),
  org("org-future-of-life-institute", { name: "Future of Life Institute", url: "https://futureoflife.org/", mission: "Steer transformative technology towards benefiting life and away from extreme large-scale risks.", legal: "US 501(c)(3) nonprofit", jurisdiction: "US", focus: ["advocacy", "policy", "grants"], programs: ["Policy advocacy", "Grants", "EU AI Act tracker"], outputs: ["artificialintelligenceact.eu", "Policy publications"], funding: "Philanthropic; disclosed on website.", conflicts: ["advocacy_context"], impact: "Prominent in policy debates; positions are advocacy, not measurement.", help: ["Follow policy work"] }),
  org("org-securebio", { name: "SecureBio", url: "https://securebio.org/", mission: "Reduce biological risks including those from AI.", legal: "US nonprofit", jurisdiction: "US", focus: ["biosecurity", "evaluations"], programs: ["Biosecurity evaluations", "Screening research"], outputs: ["Evaluation reports (non-operational)"], funding: "Philanthropic; disclosed on website.", impact: "Contributes to biological-capability evaluation methodology.", help: ["Support screening initiatives"] }),
  org("org-transluce", { name: "Transluce", url: "https://transluce.org/", mission: "Build open, scalable technology for understanding AI systems.", legal: "US nonprofit", jurisdiction: "US", focus: ["interpretability", "open_tooling"], programs: ["Investigator tools"], outputs: ["Open tools and reports"], funding: "Philanthropic; disclosed on website.", impact: "Open interpretability tooling.", help: ["Use and contribute to tools"] }),
];

function act(id, o) {
  return { id, audience: o.audience, title: o.title, description: o.description, related_intervention_ids: o.interventions, resources: o.resources ?? [], effort: o.effort, ...review(o.verified ?? "prior", "informational") };
}

const R = {
  iasr: { title: "International AI Safety Report 2026", url: "https://internationalaisafetyreport.org/publication/international-ai-safety-report-2026", source_id: "src-iasr-2026" },
  inspect: { title: "Inspect evaluation framework", url: "https://inspect.aisi.org.uk/", source_id: "src-aisi-inspect" },
  owasp: { title: "OWASP GenAI Security Project", url: "https://genai.owasp.org/", source_id: "src-owasp-genai-security" },
  nsa: { title: "NSA: MCP security design guidance", url: "https://media.defense.gov/2026/Jun/02/2003943289/-1/-1/0/CSI_MCP_SECURITY.PDF", source_id: "src-nsa-2026-mcp-security" },
  registry: { title: "The MCP Registry", url: "https://modelcontextprotocol.io/registry/about", source_id: "src-mcp-registry-about" },
  aiid: { title: "AI Incident Database", url: "https://incidentdatabase.ai/", source_id: null },
  rmf: { title: "NIST AI Risk Management Framework", url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf", source_id: "src-nist-ai-rmf-100-1" },
  rand: { title: "RAND: Securing AI Model Weights", url: "https://www.rand.org/pubs/research_reports/RRA2849-1.html", source_id: "src-rand-2024-securing-model-weights" },
  control: { title: "AI Control paper", url: "https://arxiv.org/abs/2312.06942", source_id: "src-greenblatt-2023-ai-control" },
  safetycases: { title: "Safety Cases paper", url: "https://arxiv.org/abs/2403.10462", source_id: "src-clymer-2024-safety-cases" },
  metaculus: { title: "Metaculus", url: "https://www.metaculus.com/", source_id: null },
  euact: { title: "EU AI Act GPAI guidelines", url: "https://digital-strategy.ec.europa.eu/en/library/guidelines-scope-obligations-providers-general-purpose-ai-models-under-ai-act", source_id: "src-eu-ai-act-gpai-guidelines" },
  sb53: { title: "California SB 53", url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB53", source_id: "src-ca-sb53-tfaia" },
  metr: { title: "METR time horizons", url: "https://metr.org/time-horizons/", source_id: "src-metr-time-horizons-page" },
  oecd: { title: "OECD: Defining AI incidents", url: "https://www.oecd.org/en/publications/defining-ai-incidents-and-related-terms_d1a8d965-en.html", source_id: "src-oecd-2024-defining-ai-incidents" },
};

export const actions = [
  // individuals
  act("act-individuals-learn-the-basics", { audience: "individuals", title: "Learn the foundational concepts", description: "Read a synthesis report rather than headlines: what capabilities exist, what risks experts track and where evidence is thin.", interventions: ["I26"], resources: [R.iasr], effort: "low" }),
  act("act-individuals-support-evidence-institutions", { audience: "individuals", title: "Support evidence-based institutions", description: "Back independent evaluators, incident databases and forecasting organisations that publish their methods.", interventions: ["I24", "I26"], resources: [R.aiid], effort: "low" }),
  act("act-individuals-information-hygiene", { audience: "individuals", title: "Improve your information hygiene", description: "Check provenance before sharing synthetic media; prefer primary sources; expect and verify uncertainty.", interventions: ["I27"], resources: [R.aiid], effort: "low" }),
  act("act-individuals-public-consultation", { audience: "individuals", title: "Take part in public consultation", description: "Respond to regulator consultations on frontier AI rules in your jurisdiction.", interventions: ["I17"], resources: [R.euact], effort: "moderate" }),
  act("act-individuals-report-incidents", { audience: "individuals", title: "Report verified incidents", description: "Submit documented incidents to a public incident database with sources, not screenshots.", interventions: ["I03"], resources: [R.aiid], effort: "low" }),
  act("act-individuals-avoid-amplifying-unverified", { audience: "individuals", title: "Avoid amplifying unverified claims", description: "Wait for corroboration before sharing dramatic AI claims; one press release can become hundreds of articles.", interventions: ["I26"], effort: "low" }),
  act("act-individuals-contribute-skills", { audience: "individuals", title: "Contribute professional skills", description: "Security, law, statistics, communications and operations skills are all needed by safety organisations.", interventions: ["I24"], effort: "moderate" }),
  // software engineers
  act("act-software_engineers-permission-boundaries", { audience: "software_engineers", title: "Build permission boundaries", description: "Separate what an agent may read, write and execute; enforce boundaries in code.", interventions: ["I07", "I08"], resources: [R.owasp, R.nsa], effort: "moderate" }),
  act("act-software_engineers-least-privilege", { audience: "software_engineers", title: "Implement least privilege", description: "Scope credentials per task and rotate them; never hand agents standing production access.", interventions: ["I07"], resources: [R.nsa], effort: "moderate" }),
  act("act-software_engineers-cancellation", { audience: "software_engineers", title: "Add cancellation", description: "Make every agent and sub-agent stoppable, with cancellation propagated through delegation.", interventions: ["I10"], effort: "moderate" }),
  act("act-software_engineers-log-tool-actions", { audience: "software_engineers", title: "Log tool actions", description: "Record every tool call with identity, arguments and outcome in an append-only log.", interventions: ["I08", "I10"], resources: [R.owasp], effort: "low" }),
  act("act-software_engineers-secure-mcp-servers", { audience: "software_engineers", title: "Secure MCP servers", description: "Pin server versions, verify namespaces, monitor tool-list changes and treat tool descriptions as untrusted input.", interventions: ["I11", "I12"], resources: [R.nsa, R.registry], effort: "moderate" }),
  act("act-software_engineers-sign-skills", { audience: "software_engineers", title: "Sign skills and dependencies", description: "Sign and verify skills, plugins and dependencies; refuse unsigned updates.", interventions: ["I12"], effort: "moderate" }),
  act("act-software_engineers-sandbox-agents", { audience: "software_engineers", title: "Sandbox agents", description: "Default-deny network egress and file access for agents; allowlist explicitly.", interventions: ["I06"], resources: [R.nsa], effort: "moderate" }),
  act("act-software_engineers-test-prompt-injection", { audience: "software_engineers", title: "Test for prompt injection", description: "Include injected instructions in test content and assert that policies, not prompts, decide.", interventions: ["I08"], resources: [R.owasp], effort: "low" }),
  act("act-software_engineers-deterministic-policies", { audience: "software_engineers", title: "Create deterministic safety policies", description: "Budgets, rate limits, allowlists and approval gates in the harness.", interventions: ["I08", "I09"], effort: "moderate" }),
  act("act-software_engineers-report-vulnerabilities", { audience: "software_engineers", title: "Report vulnerabilities responsibly", description: "Use coordinated disclosure for agent and MCP vulnerabilities; never publish live exploits.", interventions: ["I12"], effort: "low" }),
  // ai researchers
  act("act-ai_researchers-evaluations", { audience: "ai_researchers", title: "Work on evaluations", description: "Design evaluations for autonomy, deception and dangerous capabilities that resist gaming.", interventions: ["I01"], resources: [R.inspect, R.metr], effort: "high" }),
  act("act-ai_researchers-control", { audience: "ai_researchers", title: "Work on control", description: "Develop and test protocols that remain safe under intentional subversion.", interventions: ["I16"], resources: [R.control], effort: "high" }),
  act("act-ai_researchers-interpretability", { audience: "ai_researchers", title: "Work on interpretability", description: "Aim at detection of deceptive cognition in frontier-scale models.", interventions: ["I14"], effort: "high" }),
  act("act-ai_researchers-robustness", { audience: "ai_researchers", title: "Work on robustness", description: "Adversarial robustness of safeguards and monitors.", interventions: ["I01", "I16"], effort: "high" }),
  act("act-ai_researchers-scalable-oversight", { audience: "ai_researchers", title: "Work on scalable oversight", description: "Test oversight methods at growing capability gaps.", interventions: ["I15"], effort: "high" }),
  act("act-ai_researchers-forecasting", { audience: "ai_researchers", title: "Work on forecasting", description: "Register resolvable predictions about capabilities and evaluations.", interventions: ["I26"], resources: [R.metaculus], effort: "low" }),
  act("act-ai_researchers-red-teaming", { audience: "ai_researchers", title: "Red team", description: "Stress-test agents and safeguards under realistic incentives, publishing non-operational findings.", interventions: ["I01", "I13"], effort: "moderate" }),
  act("act-ai_researchers-monitoring", { audience: "ai_researchers", title: "Work on monitoring", description: "Runtime monitors for deployed agents that detect scope violations.", interventions: ["I16", "I10"], effort: "high" }),
  act("act-ai_researchers-alignment", { audience: "ai_researchers", title: "Work on alignment", description: "Research that reduces misgeneralisation and reward hacking.", interventions: ["I13", "I15"], effort: "high" }),
  act("act-ai_researchers-model-security", { audience: "ai_researchers", title: "Work on model security", description: "Weight security, exfiltration detection and secure inference.", interventions: ["I04"], resources: [R.rand], effort: "high" }),
  // laboratories
  act("act-laboratories-publish-safety-cases", { audience: "laboratories", title: "Publish safety cases", description: "Structured, reviewable arguments tied to evidence for each frontier deployment.", interventions: ["I19"], resources: [R.safetycases], effort: "high" }),
  act("act-laboratories-external-evaluation", { audience: "laboratories", title: "Use external evaluation", description: "Give independent evaluators pre-deployment access and publish results.", interventions: ["I02", "I01"], resources: [R.inspect], effort: "moderate" }),
  act("act-laboratories-report-incidents", { audience: "laboratories", title: "Report incidents", description: "Disclose serious incidents promptly using shared definitions.", interventions: ["I03"], resources: [R.oecd], effort: "low" }),
  act("act-laboratories-secure-weights", { audience: "laboratories", title: "Secure model weights", description: "Reach and audit a stated security level.", interventions: ["I04"], resources: [R.rand], effort: "high" }),
  act("act-laboratories-deployment-thresholds", { audience: "laboratories", title: "Define deployment thresholds", description: "Pre-commit to capability thresholds and the safeguards they trigger.", interventions: ["I01", "I20"], effort: "moderate" }),
  act("act-laboratories-support-whistleblowers", { audience: "laboratories", title: "Support whistleblowers", description: "Protect and route internal reports of safety failures.", interventions: ["I18"], resources: [R.sb53], effort: "low" }),
  act("act-laboratories-preserve-rollback", { audience: "laboratories", title: "Preserve rollback", description: "Keep the ability to withdraw a deployment quickly.", interventions: ["I20", "I10"], effort: "moderate" }),
  act("act-laboratories-staged-releases", { audience: "laboratories", title: "Conduct staged releases", description: "Release gradually with monitoring at each stage.", interventions: ["I20"], effort: "moderate" }),
  act("act-laboratories-fund-public-interest-research", { audience: "laboratories", title: "Fund public-interest research", description: "Support independent evaluation and safety research without control over results.", interventions: ["I23", "I24"], effort: "moderate" }),
  // policymakers
  act("act-policymakers-incident-reporting", { audience: "policymakers", title: "Improve incident reporting", description: "Adopt interoperable incident definitions and mandatory reporting for frontier systems.", interventions: ["I03"], resources: [R.oecd, R.euact], effort: "moderate" }),
  act("act-policymakers-support-standards", { audience: "policymakers", title: "Support standards", description: "Fund and adopt risk-management and security standards.", interventions: ["I17"], resources: [R.rmf], effort: "moderate" }),
  act("act-policymakers-fund-evaluation-infrastructure", { audience: "policymakers", title: "Fund evaluation infrastructure", description: "Public evaluation capacity that does not depend on developers.", interventions: ["I23", "I01"], resources: [R.inspect], effort: "high" }),
  act("act-policymakers-technical-capacity", { audience: "policymakers", title: "Build technical capacity", description: "Hire and retain technical staff in regulators.", interventions: ["I23"], effort: "high" }),
  act("act-policymakers-coordinate-internationally", { audience: "policymakers", title: "Coordinate internationally", description: "Align thresholds, reporting and evaluation standards across jurisdictions.", interventions: ["I17"], resources: [R.iasr], effort: "high" }),
  act("act-policymakers-proportionate-liability", { audience: "policymakers", title: "Create proportionate liability", description: "Clarify who bears the cost of harms from autonomous agents.", interventions: ["I22"], effort: "moderate" }),
  act("act-policymakers-protect-disclosure", { audience: "policymakers", title: "Protect research and disclosure", description: "Safe harbours for good-faith safety research and whistleblowers.", interventions: ["I18"], resources: [R.sb53], effort: "moderate" }),
  // funders
  act("act-funders-independent-nonprofits", { audience: "funders", title: "Support independent nonprofits", description: "Multi-year funding for evaluators and researchers independent of developers.", interventions: ["I24"], effort: "moderate" }),
  act("act-funders-open-safety-tools", { audience: "funders", title: "Fund open safety tools", description: "Maintenance of open evaluation, monitoring and provenance tooling.", interventions: ["I25"], resources: [R.inspect], effort: "moderate" }),
  act("act-funders-neglected-technical-work", { audience: "funders", title: "Fund neglected technical work", description: "Control evaluations, agent security and interpretability at frontier scale.", interventions: ["I14", "I16"], effort: "moderate" }),
  act("act-funders-forecasting-and-measurement", { audience: "funders", title: "Fund forecasting and measurement", description: "Resolvable forecasting programmes and calibration research.", interventions: ["I26"], effort: "low" }),
  act("act-funders-governance-capacity", { audience: "funders", title: "Fund governance capacity", description: "Technical capacity in regulators and standards bodies.", interventions: ["I17", "I23"], effort: "moderate" }),
  act("act-funders-avoid-publicity-incentives", { audience: "funders", title: "Avoid incentives based only on publicity", description: "Reward replication, corrections and null results, not attention.", interventions: ["I26"], effort: "low" }),
  // educators
  act("act-educators-teach-uncertainty", { audience: "educators", title: "Teach uncertainty", description: "Show intervals, disagreement and what would change a number.", interventions: ["I26"], effort: "low" }),
  act("act-educators-source-evaluation", { audience: "educators", title: "Teach source evaluation", description: "Tiers of evidence, conflicts of interest and news cascades.", interventions: ["I27"], effort: "low" }),
  act("act-educators-threat-modeling", { audience: "educators", title: "Teach threat modelling", description: "How to reason about capabilities, exposure and safeguards without operational detail.", interventions: ["I08"], effort: "moderate" }),
  act("act-educators-agent-security", { audience: "educators", title: "Teach agent security", description: "Prompt injection, least privilege and deterministic policies.", interventions: ["I07", "I08"], resources: [R.owasp], effort: "moderate" }),
  act("act-educators-current-harm-vs-speculation", { audience: "educators", title: "Distinguish current harm from speculative catastrophe", description: "Keep documented incidents separate from scenario reasoning.", interventions: ["I03"], resources: [R.aiid], effort: "low" }),
  // others
  act("act-nonprofits-publish-methods", { audience: "nonprofits", title: "Publish methods and corrections", description: "Make methodology, data and correction logs public.", interventions: ["I26"], effort: "low" }),
  act("act-auditors_red_teams-control-evaluations", { audience: "auditors_red_teams", title: "Run control evaluations", description: "Test deployment protocols against intentional subversion.", interventions: ["I16", "I02"], resources: [R.control], effort: "high" }),
  act("act-standards_bodies-registry-signing", { audience: "standards_bodies", title: "Standardise registry signing and provenance", description: "Signing, provenance and tool-change notification requirements for agent registries.", interventions: ["I11", "I12"], resources: [R.registry], effort: "moderate" }),
];
