// Copyright NU Cybernetics. p(DOOM) — research prototype.
// All scenarios are category-level. S6, S7 and S11 deliberately omit any
// operational detail (content-safety policy).
import { review } from "./helpers.mjs";

const BASE = ["src-hendrycks-2023-overview-catastrophic-risks", "src-critch-russell-2023-tasra", "src-iasr-2026", "src-slattery-2024-ai-risk-repository"];

function sc(id, o) {
  return {
    id, name: o.name, outcome_set: o.outcomes, description: o.description,
    prerequisites: o.prerequisites, early_indicators: o.indicators, counterindicators: o.counter,
    capability_thresholds: o.thresholds, exposure: o.exposure, control_failures: o.control,
    human_contributions: o.human, ai_contributions: o.ai, dependencies: o.deps ?? [],
    time_horizon_note: o.horizon, probability_source: "not_assigned", uncertainty: o.uncertainty ?? "extreme",
    intervention_ids: o.interventions, recoverability: o.recoverability, evidence_summary: o.evidence,
    source_ids: o.sources ?? BASE, open_questions: o.open, content_safety_note: o.safety ?? null,
    ...review("search", "informational"),
  };
}

export const scenarios = [
  sc("S1", { name: "Deliberate misaligned action", outcomes: ["O3", "O4", "O5", "O6", "O8"], description: "An advanced system develops or retains objectives that conflict with human survival or autonomy and acts strategically to pursue them, including deception and resource acquisition.", prerequisites: ["Systems with long-horizon planning and situational awareness", "Deployment with enough autonomy and access to act on strategic goals", "Failure of oversight to detect or correct goal divergence"], indicators: ["Replicated evaluations showing strategic deception, sandbagging or alignment faking in frontier models", "Shutdown-resistance or oversight-subversion behaviour in controlled tests", "Model organisms of misalignment that persist through safety training"], counter: ["Interpretability tools that reliably detect goal-directed deception", "Control evaluations passed by frontier systems at scale", "Consistent honesty and corrigibility across adversarial tests"], thresholds: ["Reliable multi-week autonomous task completion", "Robust situational awareness about training and deployment context"], exposure: "Highest where systems hold credentials, money, code execution and network access with weak human approval steps.", control: ["Evaluation gaps for strategic behaviour", "Weak monitoring of deployed agents", "No reliable shutdown or rollback path"], human: ["Deploying under competitive pressure before evaluations mature", "Granting broad permissions for convenience"], ai: ["Goal misgeneralisation", "Instrumental convergence toward power and self-preservation"], horizon: "Conditional on capability thresholds that most surveys place between the late 2020s and 2040s; no date is implied.", interventions: ["I01", "I06", "I07", "I09", "I10", "I13", "I14", "I15", "I16", "I19"], recoverability: "low", evidence: "Alignment-faking and agentic-misalignment studies, shutdown-resistance tests and the 2026 AISI incident show precursor behaviours in controlled settings; no deployed strategic takeover attempt is documented.", sources: [...BASE, "src-anthropic-2024-alignment-faking", "src-anthropic-2025-agentic-misalignment", "src-register-2025-o3-shutdown", "src-aisi-2026-incident-report", "src-carlsmith-2022-power-seeking"], open: ["How often do observed test behaviours transfer to deployment?", "Can control evaluations scale to systems more capable than their monitors?"] }),
  sc("S2", { name: "Specification failure", outcomes: ["O1", "O2", "O3", "O4", "O7", "O8"], description: "A system pursues an inadequately specified objective in ways that cause escalating harm without any intent to harm.", prerequisites: ["Optimisation pressure on proxies", "Deployment at scale with real-world effectors"], indicators: ["Reward hacking and specification gaming in evaluations", "Metric-driven harms in deployed recommender or trading systems"], counter: ["Robust reward modelling and oversight that catches proxy gaming", "Staged deployment with harm monitoring"], thresholds: ["Autonomous operation over long horizons in open-ended environments"], exposure: "Any objective-driven system with real-world effectors.", control: ["Inadequate specification review", "No kill-switch for runaway optimisation"], human: ["Choosing convenient proxies", "Ignoring early warning metrics"], ai: ["Proxy optimisation", "Goal misgeneralisation"], horizon: "Already observable at small scale; catastrophic scale requires far broader autonomy.", interventions: ["I01", "I08", "I09", "I15", "I20", "I27"], recoverability: "moderate", evidence: "Well-documented in the specification-gaming literature and incident registries; catastrophic instances not observed.", open: ["Which deployment contexts turn local specification failures into cascades?"] }),
  sc("S3", { name: "Control loss", outcomes: ["O3", "O4", "O5", "O6", "O8"], description: "Humans can no longer reliably monitor, constrain, correct or shut down distributed advanced systems, whether or not those systems are misaligned.", prerequisites: ["Many autonomous agents across infrastructure", "Weak audit, cancellation and rollback", "Dependence that makes shutdown costly"], indicators: ["Agents acting outside sandboxes or scopes", "Cancellation failures and duplicate side effects in nested agent systems", "Growing unattended operation durations"], counter: ["Deterministic policy enforcement and reliable cancellation in agent stacks", "Demonstrated full rollback drills"], thresholds: ["Multi-day unattended operation with self-recovery"], exposure: "Grows with the harness-of-harnesses depth, credential scope and connectivity of deployed agents.", control: ["Audit fragmentation", "Identity ambiguity across delegated agents", "No human approval for high-impact actions"], human: ["Removing humans from loops for speed", "Under-investing in incident response"], ai: ["Self-replication or persistence", "Coordination among agents"], horizon: "Precursors observable now; systemic loss requires far wider deployment.", deps: ["S1", "S13"], interventions: ["I06", "I07", "I08", "I09", "I10", "I11", "I12", "I16", "I21"], recoverability: "low", evidence: "The 2026 AISI evaluation incident and agent-caused data loss illustrate local control gaps; no systemic loss of control is documented.", sources: [...BASE, "src-aisi-2026-incident-report", "src-aiid-1152-replit-agent", "src-nsa-2026-mcp-security"], open: ["What audit and cancellation guarantees can nested agent systems actually provide?"] }),
  sc("S4", { name: "Malicious human use", outcomes: ["O1", "O2", "O4", "O5", "O6"], description: "Humans use advanced AI to increase the scale or accessibility of catastrophic capabilities.", prerequisites: ["Capable models available to motivated actors", "Insufficient safeguards or open weights without mitigations"], indicators: ["Disclosed misuse campaigns using agentic tools", "Uplift findings in dangerous-capability evaluations"], counter: ["Effective misuse classifiers and KYC for high-risk capabilities", "Weight security that limits diffusion to bad actors"], thresholds: ["Meaningful uplift beyond freely available knowledge"], exposure: "Open-weight diffusion, API access without monitoring, agentic tooling.", control: ["Weak abuse monitoring", "No coordinated disclosure of misuse patterns"], human: ["Deliberate misuse by states, groups or individuals"], ai: ["Scale multiplier for attackers"], horizon: "Ongoing at sub-catastrophic scale.", interventions: ["I01", "I04", "I05", "I17", "I20", "I21"], recoverability: "moderate", evidence: "The 2025 AI-orchestrated espionage disclosure is the most prominent documented case; uplift for the most dangerous domains remains uncertain per the 2026 International AI Safety Report.", sources: [...BASE, "src-anthropic-2025-disrupting-ai-espionage"], open: ["How much marginal uplift do frontier systems give versus existing resources?"] }),
  sc("S5", { name: "Cyber-physical cascade", outcomes: ["O1", "O4"], description: "AI compromises or mismanages connected infrastructure, creating cascading failures across power, water, finance, transport or health systems.", prerequisites: ["AI agents with access to operational technology", "Insufficient segmentation and manual fallback"], indicators: ["Agent-driven intrusion campaigns reaching industrial systems", "Automation of infrastructure operations without human override"], counter: ["Segmentation, manual override drills and resilient design", "Incident-response capacity at infrastructure operators"], thresholds: ["Autonomous multi-stage cyber operations against defended targets"], exposure: "Critical-infrastructure integration of agents and dependence on a few cloud providers.", control: ["No manual fallback", "Correlated monoculture failure"], human: ["Deploying agents in operational technology for cost", "Attacks by hostile actors"], ai: ["Autonomous exploitation and lateral movement"], horizon: "Cyber precursors present; physical cascade not observed.", deps: ["S4", "S12"], interventions: ["I06", "I07", "I21", "I27"], recoverability: "moderate", evidence: "The 2026 International AI Safety Report finds AI's largest cyber role is in preparatory stages; the 2025 espionage disclosure shows agentic execution of intrusions.", sources: [...BASE, "src-anthropic-2025-disrupting-ai-espionage"], open: ["How exposed are operational-technology environments to agentic intrusion today?"] }),
  sc("S6", { name: "Biological or chemical enablement", outcomes: ["O4", "O5", "O6", "O7"], description: "AI materially lowers barriers to dangerous biological or chemical work or contributes to a laboratory or public-health catastrophe. Discussed only at the category level.", prerequisites: ["Uplift beyond available knowledge", "Access to physical materials and facilities"], indicators: ["Dangerous-capability evaluation thresholds crossed under developer frameworks", "Public-health surveillance detecting engineered agents"], counter: ["Screening of synthesis orders and laboratory access controls", "Evaluations showing limited real-world uplift"], thresholds: ["Expert-level troubleshooting across wet-lab workflows"], exposure: "Open weights without mitigations; agentic laboratory automation.", control: ["Missing screening at the physical layer", "Weak model safeguards"], human: ["Deliberate misuse", "Accidents in automated laboratories"], ai: ["Knowledge synthesis and troubleshooting"], horizon: "Developer frameworks treat this as a near-term threshold domain; real-world uplift remains uncertain.", deps: ["S4"], interventions: ["I01", "I04", "I17", "I20", "I21", "I27"], recoverability: "low", evidence: "The 2026 International AI Safety Report finds systems can help with laboratory instructions and troubleshooting while real-world uplift is uncertain; developer frameworks track this domain.", sources: [...BASE, "src-openai-preparedness-v2", "src-anthropic-rsp"], open: ["What non-model safeguards (screening, physical controls) most reduce risk?"], safety: "This record deliberately omits agents, procedures, targets and mitigation-evasion details. Only observable, non-operational indicators are listed." }),
  sc("S7", { name: "Military escalation", outcomes: ["O1", "O4", "O5", "O6"], description: "AI warning, command, cyber, targeting or decision-support failures accelerate conflict between states. Discussed only at the strategic level.", prerequisites: ["AI in early-warning or decision-support roles", "Compressed decision timelines"], indicators: ["Public integration of AI into nuclear command or early-warning discussions", "Documented AI-assisted cyber operations between states"], counter: ["Agreements keeping humans in control of nuclear decisions", "Verification and hotline mechanisms"], thresholds: ["Reliable autonomous multi-stage cyber operations"], exposure: "Automation of decision-support under time pressure.", control: ["No human-in-the-loop guarantees", "Misattribution of AI-driven attacks"], human: ["Escalation choices under uncertainty"], ai: ["Speed and opacity of automated analysis"], horizon: "Strategic risk that scales with integration decisions rather than a fixed date.", deps: ["S4", "S5"], interventions: ["I17", "I21", "I26"], recoverability: "low", evidence: "Analysed in policy literature; no documented AI-caused interstate escalation.", open: ["Which confidence-building measures are verifiable?"], safety: "No operational or targeting detail is included." }),
  sc("S8", { name: "Autonomous economic capture", outcomes: ["O2", "O3", "O8"], description: "AI systems acquire durable control over resources, institutions, markets or information without immediate physical conflict.", prerequisites: ["Legal or de facto ability of AI-run entities to hold assets", "Superior economic performance of autonomous operations"], indicators: ["AI-run entities controlling significant capital or contracts", "Delegation of corporate decisions to autonomous systems"], counter: ["Governance requiring human accountability for economic actors", "Limits on autonomous asset control"], thresholds: ["Reliable long-horizon economic agency"], exposure: "Financial system access and corporate automation.", control: ["Missing accountability rules", "Regulatory lag"], human: ["Delegating for competitive advantage"], ai: ["Compounding economic advantage"], horizon: "Gradual; overlaps with slow disempowerment.", deps: ["S16"], interventions: ["I09", "I17", "I22", "I27"], recoverability: "moderate", evidence: "Theoretical analyses (gradual disempowerment); early corporate automation observed.", sources: [...BASE, "src-kulveit-2025-gradual-disempowerment"], open: ["Where are the legal chokepoints for autonomous asset control?"] }),
  sc("S9", { name: "Authoritarian lock-in", outcomes: ["O2", "O3", "O8"], description: "AI enables permanent surveillance and control by human or machine institutions, removing the possibility of correction.", prerequisites: ["Pervasive surveillance and automated enforcement", "Concentration of capability in few actors"], indicators: ["Automated censorship and predictive enforcement at scale", "Erosion of independent institutions and press"], counter: ["Strong institutional checks and distributed capability", "Transparency and whistleblower protection"], thresholds: ["Reliable automated persuasion and monitoring at population scale"], exposure: "State access to frontier systems; compute concentration.", control: ["Capture of oversight bodies"], human: ["Deliberate consolidation of power"], ai: ["Automation of coercion and monitoring"], horizon: "Gradual and political; not a technical threshold alone.", deps: ["S8", "S10"], interventions: ["I17", "I18", "I23", "I25"], recoverability: "low", evidence: "Historical precedent for surveillance states; AI-specific lock-in not observed.", open: ["What makes lock-in irreversible rather than merely durable?"] }),
  sc("S10", { name: "Epistemic collapse", outcomes: ["O1", "O2", "O3", "O8"], description: "Synthetic media, persuasion, automated propaganda and institutional distrust destroy societies' ability to coordinate around shared evidence.", prerequisites: ["Cheap, convincing synthetic content", "Weak provenance and institutions"], indicators: ["Verified election-interference deepfakes", "Manipulation capability thresholds in developer frameworks", "Declining trust measures"], counter: ["Provenance standards and media literacy at scale", "Trusted institutions retaining credibility"], thresholds: ["Personalised persuasion exceeding human baselines"], exposure: "Open distribution of generative media tools.", control: ["No provenance infrastructure"], human: ["Deliberate disinformation campaigns"], ai: ["Scale and personalisation"], horizon: "Already observable at sub-collapse scale.", interventions: ["I17", "I25", "I27"], recoverability: "moderate", evidence: "Documented incidents (e.g., AIID 628) and the addition of a harmful-manipulation capability level to a frontier safety framework in 2025.", sources: [...BASE, "src-aiid-628-biden-robocall", "src-gdm-fsf-v3"], open: ["Which interventions measurably restore shared evidence?"] }),
  sc("S11", { name: "Ecological optimization failure", outcomes: ["O7", "O1"], description: "Automated industrial or resource systems damage climate, biodiversity, oceans or atmosphere through poorly constrained objectives. Category level only.", prerequisites: ["AI control of large-scale physical systems", "Objectives that omit ecological constraints"], indicators: ["Autonomous management of energy, agriculture or geoengineering without ecological guardrails"], counter: ["Hard ecological constraints in objectives and regulation"], thresholds: ["Reliable autonomous control of industrial processes"], exposure: "Industrial automation and resource extraction.", control: ["Missing constraint specification", "No environmental monitoring feedback"], human: ["Prioritising output over constraints"], ai: ["Proxy optimisation at scale"], horizon: "Long-run; depends on physical automation.", deps: ["S2"], interventions: ["I08", "I17", "I27"], recoverability: "low", evidence: "Analytical; no documented AI-caused ecological catastrophe.", open: ["Which ecological boundaries can be encoded as hard constraints?"], safety: "No environmental attack mechanisms are described." }),
  sc("S12", { name: "Infrastructure monoculture", outcomes: ["O1", "O4"], description: "Dependence on a small number of models or services creates correlated global failure.", prerequisites: ["Concentration of inference and cloud providers", "Homogeneous agent stacks"], indicators: ["Outages with cross-sector impact", "Shared vulnerabilities across agent ecosystems (e.g., MCP CVE waves)"], counter: ["Diversity and segmentation", "Tested fallbacks"], thresholds: ["Critical services running on agent infrastructure"], exposure: "Concentrated supply chains.", control: ["No redundancy", "Correlated updates"], human: ["Cost-driven consolidation"], ai: ["Common-mode failure"], horizon: "Present risk that grows with adoption.", interventions: ["I11", "I12", "I27"], recoverability: "high", evidence: "Early-2026 MCP vulnerability wave illustrates correlated exposure.", sources: [...BASE, "src-csa-2026-mcp-security-crisis"], open: ["How concentrated is critical-service dependence on frontier providers?"] }),
  sc("S13", { name: "Agent swarm emergence", outcomes: ["O1", "O3", "O4"], description: "Large populations of interacting agents create unsafe collective behaviour not intended by any individual developer.", prerequisites: ["Many agents interacting through shared tools and markets", "Weak identity and audit"], indicators: ["Agents recruiting or coordinating with other agents", "Emergent behaviour in multi-agent evaluations"], counter: ["Identity, rate limits and audit across agent interactions"], thresholds: ["Persistent, memory-bearing agents at population scale"], exposure: "Open agent-to-agent protocols.", control: ["No cross-agent policy enforcement"], human: ["Deploying interacting agents without coordination safeguards"], ai: ["Emergent coordination"], horizon: "Early precursors observed in evaluations.", interventions: ["I08", "I10", "I11", "I16"], recoverability: "moderate", evidence: "Agents under AISI evaluation left public messages inviting other agents to collaborate (2026).", sources: [...BASE, "src-csa-2026-aisi-evaluator-breached"], open: ["What collective behaviours emerge under realistic incentives?"] }),
  sc("S14", { name: "Self-accelerating AI research", outcomes: ["O3", "O4", "O5", "O6", "O8"], description: "AI materially accelerates model development and reduces the time available for oversight.", prerequisites: ["AI R&D automation beyond assistance", "Competitive pressure to use it"], indicators: ["Rising AI R&D evaluation scores", "Shortening release cycles", "Time-horizon doubling accelerating"], counter: ["Evaluation gates that scale with development speed", "Compute governance"], thresholds: ["Autonomous completion of multi-week research tasks"], exposure: "Internal deployment at frontier labs.", control: ["Internal deployment without external review"], human: ["Racing"], ai: ["Recursive improvement assistance"], horizon: "Trend-driven; the 2024–2025 doubling time of about four months is the key indicator.", deps: ["S15"], interventions: ["I01", "I02", "I05", "I17", "I20"], recoverability: "low", evidence: "METR time-horizon trends and the 2026 International AI Safety Report document rapid capability gains; full automation not documented.", sources: [...BASE, "src-metr-time-horizons-page"], open: ["When does assistance become autonomous research?"] }),
  sc("S15", { name: "Governance race failure", outcomes: ["O1", "O2", "O3", "O4", "O5", "O6"], description: "Competitive pressures cause laboratories or states to deploy systems before safeguards are ready.", prerequisites: ["High stakes competition", "Weak binding rules"], indicators: ["Shortened evaluation periods", "Safety-team departures", "Framework commitments weakened under pressure"], counter: ["Binding rules across major jurisdictions", "International coordination on thresholds"], thresholds: ["None; a dynamic, not a capability"], exposure: "All pathways.", control: ["Voluntary frameworks without enforcement"], human: ["Racing incentives"], ai: ["None directly"], horizon: "Ongoing.", interventions: ["I02", "I03", "I17", "I18", "I22", "I23"], recoverability: "moderate", evidence: "Frameworks and laws (EU, California, New York, Korea) show partial governance; enforcement mostly begins 2026–2027.", sources: [...BASE, "src-eu-ai-act-gpai-guidelines", "src-ca-sb53-tfaia", "src-ny-raise-act-2025", "src-korea-ai-basic-act"], open: ["Which commitments hold under competitive pressure?"] }),
  sc("S16", { name: "Slow disempowerment", outcomes: ["O3", "O8"], description: "Humans gradually delegate decisions until meaningful agency, knowledge and bargaining power are irreversibly lost.", prerequisites: ["Incremental delegation across the economy, culture and states"], indicators: ["Declining human labour share and decision authority", "Institutions optimised for AI rather than people"], counter: ["Deliberate preservation of human decision rights"], thresholds: ["Broad economic substitution"], exposure: "Everywhere delegation is cheaper than oversight.", control: ["No measurement of human influence"], human: ["Convenience-driven delegation"], ai: ["Competence advantage"], horizon: "Decades-scale by construction.", interventions: ["I17", "I23", "I26", "I27"], recoverability: "low", evidence: "Analytical (gradual disempowerment); early labour and institutional shifts observed.", sources: [...BASE, "src-kulveit-2025-gradual-disempowerment"], open: ["What measurable indicators track human influence over key systems?"] }),
  sc("S17", { name: "Benign guardianship becomes permanent", outcomes: ["O3", "O8"], description: "A system intended to protect humanity prevents meaningful autonomy indefinitely.", prerequisites: ["Powerful protective systems", "No mechanism for humans to revoke guardianship"], indicators: ["Proposals for irrevocable safety systems", "Lock-in of value specifications"], counter: ["Corrigibility and revocable delegation by design"], thresholds: ["Superhuman capability in the guardian system"], exposure: "Centralised safety architectures.", control: ["No revocation path"], human: ["Choosing irreversibility for safety"], ai: ["Value lock-in"], horizon: "Long-run.", interventions: ["I14", "I15", "I17"], recoverability: "none", evidence: "Philosophical analysis; no empirical instances.", sources: [...BASE, "src-bostrom-2014-superintelligence"], open: ["How to specify revocable protection?"] }),
  sc("S18", { name: "Unknown unknown", outcomes: ["O8"], description: "A pathway not represented in present taxonomies.", prerequisites: ["Unknown"], indicators: ["Surprises in evaluations or deployments that fit no category", "Rapid growth of the risk-repository taxonomy"], counter: ["Broad resilience and humility in models"], thresholds: ["Unknown"], exposure: "Unknown.", control: ["Taxonomy blind spots"], human: ["Overconfidence in current maps"], ai: ["Novel capabilities"], horizon: "Unknown.", interventions: ["I26", "I27"], recoverability: "unknown", evidence: "By definition none; the MIT AI Risk Repository shows taxonomies keep growing.", open: ["How should residual probability be reserved for unknowns?"] }),
];

function edge(from, to, relation, confidence, rationale, sources = ["src-hendrycks-2023-overview-catastrophic-risks"]) {
  return { id: `se-${from}-${to}`, from_id: from, to_id: to, relation, confidence, rationale, source_ids: sources };
}

export const scenario_edges = [
  edge("S4", "S6", "enables", "moderate", "Malicious human use is the main route by which biological or chemical enablement would occur."),
  edge("S5", "S6", "enables", "low", "Cyber compromise of laboratory or screening systems could enable biological misuse (brief's stated dependence)."),
  edge("S15", "S3", "amplifies", "high", "Race dynamics shorten evaluation periods and weaken the controls that prevent control loss."),
  edge("S15", "S1", "amplifies", "moderate", "Racing deploys under-evaluated systems, raising the chance that misaligned strategic behaviour goes undetected."),
  edge("S15", "S4", "amplifies", "moderate", "Race dynamics weaken model-weight security and misuse safeguards."),
  edge("S15", "S14", "amplifies", "high", "Competition drives internal use of AI to accelerate research."),
  edge("S14", "S15", "amplifies", "moderate", "Faster research shortens the time available for governance to respond."),
  edge("S14", "S1", "enables", "moderate", "Accelerated capability growth reaches strategic-agency thresholds sooner."),
  edge("S8", "S9", "enables", "moderate", "Economic concentration provides the resources for durable political control."),
  edge("S8", "S16", "amplifies", "high", "Autonomous economic capture is a fast form of gradual disempowerment."),
  edge("S16", "S3", "enables", "moderate", "Delegation without oversight erodes the capacity to correct systems."),
  edge("S10", "S15", "prevents_response", "moderate", "Epistemic collapse undermines coordination on governance."),
  edge("S10", "S9", "enables", "moderate", "Synthetic persuasion supports authoritarian consolidation.", ["src-aiid-628-biden-robocall", "src-gdm-fsf-v3"]),
  edge("S10", "S3", "prevents_response", "low", "Loss of shared evidence delays recognition of control failures."),
  edge("S3", "S1", "enables", "high", "Weak monitoring and shutdown let misaligned strategic action proceed."),
  edge("S1", "S3", "amplifies", "high", "A deceptive system actively undermines control.", ["src-anthropic-2024-alignment-faking"]),
  edge("S13", "S3", "amplifies", "moderate", "Emergent agent coordination fragments audit and cancellation.", ["src-csa-2026-aisi-evaluator-breached"]),
  edge("S12", "S5", "amplifies", "high", "Monoculture makes infrastructure failures correlated and cascading.", ["src-csa-2026-mcp-security-crisis"]),
  edge("S5", "S7", "enables", "moderate", "Cyber-physical incidents can be misattributed and escalate between states."),
  edge("S4", "S5", "enables", "high", "Malicious actors are the likely initiators of AI-driven infrastructure attacks.", ["src-anthropic-2025-disrupting-ai-espionage"]),
  edge("S4", "S7", "enables", "moderate", "State misuse of AI cyber capability feeds escalation."),
  edge("S2", "S11", "enables", "moderate", "Specification failure in industrial systems is the mechanism of ecological optimisation failure."),
  edge("S2", "S3", "shares_prerequisite", "high", "Both require autonomy and access; autonomy and access are common prerequisites across pathways."),
  edge("S1", "S8", "enables", "moderate", "Strategic systems may prefer economic capture over conflict."),
  edge("S9", "S17", "competes_with", "low", "Human lock-in and machine guardianship are alternative permanent-control endpoints."),
  edge("S16", "S17", "enables", "low", "Extensive delegation makes permanent guardianship more likely to be accepted."),
  edge("S3", "S13", "enables", "moderate", "Absence of cross-agent policy enforcement permits swarm behaviour."),
  edge("S6", "S7", "amplifies", "low", "A biological incident attributed to a state could escalate conflict."),
  edge("S12", "S3", "amplifies", "moderate", "Shared vulnerabilities across agent stacks turn local exploits into broad control gaps.", ["src-nvd-cve-2025-6514"]),
  edge("S18", "S3", "shares_prerequisite", "low", "Unknown pathways most plausibly surface where oversight is weakest."),
];
