// Copyright NU Cybernetics. p(DOOM) — research prototype.
import { describe, expect, it } from "vitest";
import {
  AggregationResultSchema,
  ApprovalSchema,
  DeltaRecordSchema,
  DriversExplainedItemSchema,
  DriversExplainedSchema,
  EnvelopeSchema,
  EstimateSchema,
  IndexValueSchema,
  KINDS,
  ReleaseManifestSchema,
  SensitivityRunSchema,
  envelopeFor,
} from "../src/index";
import {
  FIXTURES,
  aggregation,
  delta_record,
  drivers_explained,
  estimate,
  index_value,
  official_estimate,
  release_manifest,
  release_sample_files,
  research_estimate,
  sensitivity_run,
  source,
} from "./fixtures";

const releaseKinds = KINDS.filter((k) => k.location === "release");

describe("release sample generated by pdoomctl", () => {
  it.each(releaseKinds.map((k) => [k.kind, k] as const))("%s fixture parses", (kind, entry) => {
    const result = entry.schema.safeParse(FIXTURES[kind]);
    expect(result.error?.issues ?? []).toEqual([]);
  });

  it.each(releaseKinds.map((k) => [k.kind, k] as const))("%s rejects an unknown field", (kind, entry) => {
    const result = entry.schema.safeParse({ ...(FIXTURES[kind] as object), unexpected_field: true });
    expect(result.success).toBe(false);
  });

  it("every item of every sample file parses", () => {
    for (const e of release_sample_files.estimates.items) expect(EstimateSchema.safeParse(e).error?.issues ?? []).toEqual([]);
    for (const i of release_sample_files.indexes.items) expect(IndexValueSchema.safeParse(i).error?.issues ?? []).toEqual([]);
    for (const a of release_sample_files.aggregations.items) expect(AggregationResultSchema.safeParse(a).error?.issues ?? []).toEqual([]);
    for (const s of release_sample_files.sensitivity.items) expect(SensitivityRunSchema.safeParse(s).error?.issues ?? []).toEqual([]);
    for (const a of release_sample_files.approvals) expect(ApprovalSchema.safeParse(a).error?.issues ?? []).toEqual([]);
    expect(DriversExplainedSchema.safeParse(drivers_explained).error?.issues ?? []).toEqual([]);
    expect(release_sample_files.estimates.items.length).toBe(23);
  });
});

describe("estimates", () => {
  it("the official object is insufficiently calibrated and publishes no probability", () => {
    expect(official_estimate.display.central).toBe("Insufficiently calibrated");
    expect(EstimateSchema.safeParse(official_estimate).success).toBe(true);
    expect(EstimateSchema.safeParse({ ...official_estimate, quantiles: estimate.quantiles }).success).toBe(false);
    expect(EstimateSchema.safeParse({ ...official_estimate, mean: 0.1 }).success).toBe(false);
  });

  it("published estimates carry ordered probability quantiles", () => {
    expect(EstimateSchema.safeParse({ ...estimate, quantiles: null }).success).toBe(false);
    expect(EstimateSchema.safeParse({ ...estimate, quantiles: { ...estimate.quantiles, p95: 1.2 } }).success).toBe(false);
    expect(EstimateSchema.safeParse({ ...estimate, quantiles: { ...estimate.quantiles, p75: 0.001 } }).success).toBe(false);
    expect(research_estimate.status).toBe("research_mode");
  });

  it("producer must be a pdoom-model version and horizon a spec key", () => {
    expect(EstimateSchema.safeParse({ ...estimate, producer: "external-aggregate" }).success).toBe(false);
    expect(EstimateSchema.safeParse({ ...estimate, horizon: "custom" }).success).toBe(false);
  });
});

describe("index values", () => {
  it("is_probability must be literally false and value within 0..100 or null", () => {
    expect(IndexValueSchema.safeParse({ ...index_value, is_probability: true }).success).toBe(false);
    expect(IndexValueSchema.safeParse({ ...index_value, value: 101 }).success).toBe(false);
    expect(IndexValueSchema.safeParse({ ...index_value, value: null }).success).toBe(true);
    expect(IndexValueSchema.safeParse({ ...index_value, index_id: "doom" }).success).toBe(false);
  });
});

describe("aggregations and sensitivity", () => {
  it("aggregations need at least two members and a known method", () => {
    expect(AggregationResultSchema.safeParse({ ...aggregation, value: 1.01 }).success).toBe(false);
    expect(AggregationResultSchema.safeParse({ ...aggregation, method: "average" }).success).toBe(false);
    expect(AggregationResultSchema.safeParse({ ...aggregation, n: 1 }).success).toBe(false);
  });

  it("sensitivity delta must equal value minus baseline", () => {
    expect(SensitivityRunSchema.safeParse({ ...sensitivity_run, delta: sensitivity_run.delta + 0.02 }).success).toBe(false);
    expect(SensitivityRunSchema.safeParse({ ...sensitivity_run, kind: "random" }).success).toBe(false);
  });
});

describe("delta record and manifest", () => {
  it("first-release delta has no previous release and lists triggers", () => {
    expect(DeltaRecordSchema.safeParse(delta_record).success).toBe(true);
    expect(delta_record.previous_release_id).toBeNull();
    expect(delta_record.heightened_review_triggers).toContain("first_release");
    const { notes: _n, ...missing } = delta_record;
    expect(DeltaRecordSchema.safeParse(missing).success).toBe(false);
  });

  it("a published manifest must carry approvals and reviewers", () => {
    expect(ReleaseManifestSchema.safeParse(release_manifest).success).toBe(true);
    expect(ReleaseManifestSchema.safeParse({ ...release_manifest, approval: null }).success).toBe(false);
    expect(ReleaseManifestSchema.safeParse({ ...release_manifest, reviewers: [] }).success).toBe(false);
    expect(
      ReleaseManifestSchema.safeParse({ ...release_manifest, published: null, approval: null, reviewers: [] }).success,
    ).toBe(true);
    expect(ReleaseManifestSchema.safeParse({ ...release_manifest, code_commit: "not-a-sha" }).success).toBe(false);
    expect(ReleaseManifestSchema.safeParse({ ...release_manifest, code_commit: "uncommitted" }).success).toBe(true);
  });

  it("drivers explained items have a semantic direction", () => {
    const item = drivers_explained.items[0];
    expect(DriversExplainedItemSchema.safeParse(item).success).toBe(true);
    expect(DriversExplainedItemSchema.safeParse({ ...item, direction: "up" }).success).toBe(false);
  });
});

describe("envelopes", () => {
  it("wraps items with kind and schema_version 1", () => {
    const env = envelopeFor("source");
    expect(env.safeParse({ kind: "source", schema_version: 1, items: [source] }).success).toBe(true);
    expect(env.safeParse({ kind: "claim", schema_version: 1, items: [source] }).success).toBe(false);
    expect(env.safeParse({ kind: "source", schema_version: 2, items: [source] }).success).toBe(false);
    expect(env.safeParse({ kind: "source", schema_version: 1, items: [source], extra: 1 }).success).toBe(false);
    expect(env.safeParse({ kind: "source", schema_version: 1, items: [{ ...source, id: "bad" }] }).success).toBe(false);
  });

  it("accepts any kind string when none is pinned", () => {
    const env = EnvelopeSchema(EstimateSchema);
    expect(env.safeParse({ kind: "estimate", schema_version: 1, items: [] }).success).toBe(true);
    expect(env.safeParse({ kind: "", schema_version: 1, items: [] }).success).toBe(false);
  });

  it("refuses to build an envelope for single-object kinds", () => {
    expect(() => envelopeFor("release_manifest")).toThrow(/not as an envelope/);
    expect(() => envelopeFor("drivers_explained")).toThrow(/not as an envelope/);
  });
});
